/****** Object:  Procedure [dbo].[sp_3040_ImportarCustodia]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [dbo].[sp_3040_ImportarCustodia]
    @p_idFundo INT, 
    @p_dtPosicao DATETIME,
    @user VARCHAR(50), 
    @cdError INT OUTPUT, 
    @dsError VARCHAR(500) OUTPUT,
    @debug INT = 0
WITH RECOMPILE
AS
BEGIN
    SET NOCOUNT ON

	DECLARE @idFundo INT = @p_idFundo, 
			@dtPosicao DATETIME = @p_dtPosicao

    DECLARE @inicio DATETIME,
            @qtImpOp INT, 
            @dtImpOp DATETIME,
            @qtImpCli INT, 
            @dtImpCli DATETIME,
			@minDate DATE,
			@maxDate DATE
    
    SET @inicio = GETDATE()
    SET @qtImpOp = 0
    SET @qtImpCli = 0

    DECLARE	@cnpjFundo VARCHAR(14), 
			@nomeFundo VARCHAR(100), 
			@TpFundo VARCHAR(MAX),
			@data DATETIME;

    --DADOS NACESSÁRIOS PARA EXECUÇÃO
    SELECT @nomeFundo = NM_FUNDO,
           @data = GETDATE(), 
           @cnpjFundo = CD_CNPJ_FUNDO,
		   @TpFundo = TP_FUNDO
    FROM TB_3040_BAS_FUNDO 
	WHERE ID_FUNDO = @idFundo

---------INICIO:::: SETANDO VARIAVEIS CUTODIA 1 E 2
	DECLARE @ID_FUNDO_CUSTODIA INT,
	        @ID_FUNDO_CUSTODIA_2 INT

	SELECT TOP 1 @ID_FUNDO_CUSTODIA = F.ID_FUNDO
	FROM FIDC_CUSTODIA_HML.dbo.TB_FUNDO F
	WHERE F.NU_CNPJ COLLATE DATABASE_DEFAULT = @cnpjFundo

	SELECT TOP 1 @ID_FUNDO_CUSTODIA_2 = F.ID_FUNDO
	FROM FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO F
	WHERE F.NU_CNPJ COLLATE DATABASE_DEFAULT = @cnpjFundo
---------FIM:::: SETANDO VARIAVEIS CUTODIA 1 E 2

    IF (@nomeFundo IS NULL) 
    BEGIN
        IF (@debug = 1)
        BEGIN
            PRINT 'Fundo informado não existe'
        END

        SET @cdError = 1
        SET @dsError = 'Fundo informado não existe'
        RETURN
    END

    IF NOT EXISTS (SELECT * 
	               FROM TB_3040_DP_PADRAO 
				   WHERE ID_FUNDO = @idFundo) 
    BEGIN
    
        IF (@debug = 1)
        BEGIN
            PRINT 'Não foi encontrado De/Para Padrão para o fundo ' + @nomeFundo
        END

        SET @cdError = 2
            SET @dsError = 'Não foi encontrado De/Para Padrão para o fundo ' + @nomeFundo
        RETURN
    END

	--GISELE PEDIU QUE PARA ESTES FUNDOS ELA NAO QUER NO MOMENTO AS INFORMAÇÕES DO CUSTODIA
	--VERIFICAR DEPOIS A NECESSIDADE DE UMA FUNCIONALIDADE QUE PERMITA A IMPORTAÇÃO CA INFORMAÇÃO DO SISTEMA DE ATIVOS E/OU CUSTODIA
    --16503123000185 FIDC MULTISEGMENTOS NPL IPANEMA III - NP
    --14109346000137 FIDC MULTISEGMENTOS NPL IPANEMA II - NP
	--16503113000140 FIDC MULTISEGMENTOS NPL IPANEMA IV - NÃO PADRONIZADO
	--24814759000176 CAPTALYS FIDC NP MAIS LOTES
	--26405883000103 FIDC MULTSEGMENTOS NPL IPANEMA VI - NP
	IF(@cnpjFundo IN('16503123000185',
	                 '14109346000137',
					 '16503113000140',
					 '24814759000176',
					 '26405883000103'))
	BEGIN 
		  SET @cdError = 0;
          SET @dsError = 'Importação executada com sucesso'
          RETURN @cdError
	END
    
    IF (@debug = 1)
    BEGIN
        PRINT 'Importando fundo ' + @nomeFundo
    END

	SELECT	@minDate = DATEADD(dd, -(DAY(@dtPosicao)-1), @dtPosicao),
	        @maxDate = DATEADD(dd, -(DAY(DATEADD(mm, 1, @dtPosicao))), DATEADD(mm, 1, @dtPosicao))

	IF(@TpFundo IN('NORMAL','HIBRIDO')) --SE FOR PADRONIZADO OU HIBRIDO
	BEGIN 

			--IMPORTA POSIÇÃO DO CUSTÓDIA PARA FUNDOS PADRONIZADOS - BASE 1
			INSERT INTO TB_3040_IMP_OPERACAO (
						CNPJ_FUNDO,
						DT_POSICAO,
						CD_CONTRATO_CEDENTE,
						CD_CONTRATO_SACADO,
						DOC_ORIGINADOR,
						ID_SISTEMA_ORIGEM,
						CD_SISTEMA_ORIGEM,
						TP_ATIVO,
						DS_CONTA_COSIF,
						FL_COOBRIGACAO,
						DT_AQUISICAO,
						DT_VENCIMENTO,
						TX_OPERACAO,
						VL_AQUISICAO,
						VL_NOMINAL,
						VL_PERC_COOBRIGACAO,
						VL_PERC_SUBORDINACAO,
						VL_PDD,
						VL_PERC_INDEXADOR,
						DOC_CEDENTE,
						DOC_SACADO,
						CD_NATUREZA,
						CD_MODALIDADE,
						CD_ORIG_RECURSOS,
						CD_INDEXADOR,
						CD_VAR_CAMB,
						CD_CARAC_ESPEC,
						CD_RATING,
						CD_VINC_ME,
						CD_PRAZO_PROV,
						CD_DESEMPENHO,
						DS_NU_DOCUMENTO,
						ID_RECEBIVEL,
						ID_ARQUIVO,
						NUM_CONTRATO_C3,
						IC_BAIXAR_ATIVO,
						IC_RECOMPRA)
				SELECT      CONVERT(VARCHAR(14), f.NU_CNPJ)					COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
							CONVERT(DATE, e.DT)								AS    DT_POSICAO,
							CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
						    CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)          COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, ---
							CONVERT(VARCHAR(14), o.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
							CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
							'FRT'											COLLATE DATABASE_DEFAULT AS    CD_SISTEMA_ORIGEM,
							CONVERT(VARCHAR(40), t.NM_TIPO_RECEBIVEL)		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
							CONVERT(VARCHAR(100), NULL)						COLLATE DATABASE_DEFAULT AS    DS_CONTA_COSIF,
							CONVERT(BIT, r.IC_COOBRIGACAO)					AS    FL_COOBRIGACAO,
							CONVERT(DATE, r.DT_AQUISICAO)					AS    DT_AQUISICAO, -- ALTERADO PARA RIO TIBAGI CONVERT(DATE, r.DT_AQUISICAO)                AS    DT_AQUISICAO, HELDER 14-07
							CONVERT(DATE, r.DT_VENCIMENTO)					AS    DT_VENCIMENTO,
							CONVERT(NUMERIC(25,10), ROUND(r.TX_CESSAO, 10)) AS    TX_OPERACAO,
							CONVERT(NUMERIC(19,4), ROUND(r.VL_AQUISICAO,4)) AS    VL_AQUISICAO,                                            
							CONVERT(NUMERIC(19,4), ROUND(E.VL_PRESENTE,4))	AS    VL_PRESENTE,  
							CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_COOBRIGACAO,
							CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_SUBORDINACAO,
							CONVERT(NUMERIC(19,4), ROUND(e.VL_PDD,4))		AS    VL_PDD,
							CONVERT(NUMERIC(3,2), ROUND(NULL,2))			AS    VL_PERC_INDEXADOR,
							CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
							CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
							CONVERT(VARCHAR(2), NULL)						AS    CD_NATUREZA, -- ANEXO 02   
							CONVERT(VARCHAR(4), NULL)						AS    CD_MODALIDADE, -- ANEXO 03
							CONVERT(VARCHAR(4), NULL)						AS    CD_ORIG_RECURSOS, -- ANEXO 04
							CONVERT(VARCHAR(2), NULL)						AS    CD_INDEXADOR, -- ANEXO 05
							CONVERT(VARCHAR(3), NULL)						AS    CD_VAR_CAMB, -- ANEXO 06
							CONVERT(VARCHAR(2), NULL)						AS    CD_CARAC_ESPEC, -- ANEXO 08
							CONVERT(VARCHAR(2), fp.DS_RISCO_ATRASO)		    COLLATE DATABASE_DEFAULT AS    CD_RATING, -- ANEXO 17 - RATING DO PDD DO CUSTÓDIA --- 
							CONVERT(VARCHAR(1), NULL)						AS    CD_VINC_ME, -- ANEXO 18
							CONVERT(VARCHAR(1), NULL)						AS    CD_PRAZO_PROV, -- ANEXO 19
							CONVERT(VARCHAR(2), NULL)						AS    CD_DESEMPENHO, -- ANEXO 28
							r.DS_NU_DOCUMENTO                               COLLATE DATABASE_DEFAULT AS    DS_NU_DOCUMENTO,
					    	e.ID_RECEBIVEL,
							r.ID_ARQUIVO,
							CONVERT(VARCHAR(14), R.NUM_CONTRATO_C3)         COLLATE DATABASE_DEFAULT AS    NUM_CONTRATO_C3,
					    	0                                               AS    IC_BAIXAR_ATIVO,
					    	0                                               AS    IC_RECOMPRA
				FROM          FIDC_CUSTODIA_HML.dbo.TB_ESTOQUE                  AS    e    WITH (NOLOCK)
				INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO                    AS    f    WITH (NOLOCK) ON  (e.ID_FUNDO            =    f.ID_FUNDO)
				INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL                AS    r    WITH (NOLOCK) ON  (r.ID_RECEBIVEL        =    e.ID_RECEBIVEL)
				INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_RECEBIVEL           AS    t    WITH (NOLOCK) ON  (t.ID_TIPO_RECEBIVEL   =    r.ID_TIPO_RECEBIVEL)
				INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE            AS    c    WITH (NOLOCK) ON  (r.ID_CEDENTE          =    c.ID_CEDENTE)
				INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO             AS    s    WITH (NOLOCK) ON  (r.ID_SACADO           =    s.ID_SACADO)
				INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_PESSOA                   AS    o    WITH (NOLOCK) ON  (r.ID_ORIGINADOR       =    o.ID_PESSOA)
				INNER JOIN	  FIDC_CUSTODIA_HML.dbo.TB_FAIXA_PDD				 AS    fp   WITH (NOLOCK) ON  (e.ID_FAIXA_PDD		 =    fp.ID_FAIXA_PDD)
				WHERE          e.DT        =    @dtPosicao
				AND            f.NU_CNPJ   =    @cnpjFundo
				AND			   R.VL_AQUISICAO <> 0 
				AND			   R.VL_NOMINAL <> 0   

				UNION ALL

				SELECT      CONVERT(VARCHAR(14), f.NU_CNPJ)					COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
							CONVERT(DATE, e.DT)								AS    DT_POSICAO,
							CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
						    CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)          COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, ---
							CONVERT(VARCHAR(14), o.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
							CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
							'FRT'											COLLATE DATABASE_DEFAULT AS    CD_SISTEMA_ORIGEM,
							CONVERT(VARCHAR(40), t.NM_TIPO_RECEBIVEL)		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
							CONVERT(VARCHAR(100), NULL)						COLLATE DATABASE_DEFAULT AS    DS_CONTA_COSIF,
							CONVERT(BIT, r.IC_COOBRIGACAO)					AS    FL_COOBRIGACAO,
							CONVERT(DATE, r.DT_AQUISICAO)					AS    DT_AQUISICAO, -- ALTERADO PARA RIO TIBAGI CONVERT(DATE, r.DT_AQUISICAO)                AS    DT_AQUISICAO, HELDER 14-07
							CONVERT(DATE, r.DT_VENCIMENTO)					AS    DT_VENCIMENTO,
							CONVERT(NUMERIC(25,10), ROUND(r.TX_CESSAO, 10)) AS    TX_OPERACAO,
							CONVERT(NUMERIC(19,4), ROUND(r.VL_AQUISICAO,4)) AS    VL_AQUISICAO,                                            
							CONVERT(NUMERIC(19,4), ROUND(E.VL_PRESENTE,4))	AS    VL_PRESENTE,  
							CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_COOBRIGACAO,
							CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_SUBORDINACAO,
							CONVERT(NUMERIC(19,4), ROUND(e.VL_PDD,4))		AS    VL_PDD,
							CONVERT(NUMERIC(3,2), ROUND(NULL,2))			AS    VL_PERC_INDEXADOR,
							CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
							CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
							CONVERT(VARCHAR(2), NULL)						AS    CD_NATUREZA, -- ANEXO 02   
							CONVERT(VARCHAR(4), NULL)						AS    CD_MODALIDADE, -- ANEXO 03
							CONVERT(VARCHAR(4), NULL)						AS    CD_ORIG_RECURSOS, -- ANEXO 04
							CONVERT(VARCHAR(2), NULL)						AS    CD_INDEXADOR, -- ANEXO 05
							CONVERT(VARCHAR(3), NULL)						AS    CD_VAR_CAMB, -- ANEXO 06
							CONVERT(VARCHAR(2), NULL)						AS    CD_CARAC_ESPEC, -- ANEXO 08
							CONVERT(VARCHAR(2), fp.DS_RISCO_ATRASO)		    COLLATE DATABASE_DEFAULT AS    CD_RATING, -- ANEXO 17 - RATING DO PDD DO CUSTÓDIA --- 
							CONVERT(VARCHAR(1), NULL)						AS    CD_VINC_ME, -- ANEXO 18
							CONVERT(VARCHAR(1), NULL)						AS    CD_PRAZO_PROV, -- ANEXO 19
							CONVERT(VARCHAR(2), NULL)						AS    CD_DESEMPENHO, -- ANEXO 28
							r.DS_NU_DOCUMENTO                               COLLATE DATABASE_DEFAULT AS    DS_NU_DOCUMENTO,
					    	e.ID_RECEBIVEL,
							r.ID_ARQUIVO,
							CONVERT(VARCHAR(14), R.NUM_CONTRATO_C3)         COLLATE DATABASE_DEFAULT AS    NUM_CONTRATO_C3,
					    	0                                               AS    IC_BAIXAR_ATIVO,
					    	0                                               AS    IC_RECOMPRA
				FROM          FIDC_CUSTODIA_HML_2.dbo.TB_ESTOQUE                  AS    e    WITH (NOLOCK)
				INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO                    AS    f    WITH (NOLOCK) ON  (e.ID_FUNDO            =    f.ID_FUNDO)
				INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL                AS    r    WITH (NOLOCK) ON  (r.ID_RECEBIVEL        =    e.ID_RECEBIVEL)
				INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_RECEBIVEL           AS    t    WITH (NOLOCK) ON  (t.ID_TIPO_RECEBIVEL   =    r.ID_TIPO_RECEBIVEL)
				INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE            AS    c    WITH (NOLOCK) ON  (r.ID_CEDENTE          =    c.ID_CEDENTE)
				INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO             AS    s    WITH (NOLOCK) ON  (r.ID_SACADO           =    s.ID_SACADO)
				INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_PESSOA                   AS    o    WITH (NOLOCK) ON  (r.ID_ORIGINADOR       =    o.ID_PESSOA)
				INNER JOIN	  FIDC_CUSTODIA_HML_2.dbo.TB_FAIXA_PDD				 AS    fp   WITH (NOLOCK) ON  (e.ID_FAIXA_PDD		 =    fp.ID_FAIXA_PDD)
				WHERE          e.DT        =    @dtPosicao
				AND            f.NU_CNPJ   =    @cnpjFundo
				AND			   R.VL_AQUISICAO <> 0 
				AND			   R.VL_NOMINAL <> 0

			SET @qtImpOp = @@ROWCOUNT
			SET @dtImpOp = GETDATE()

			IF (@debug = 1)
			BEGIN
				PRINT 'Total de operações: ' + CONVERT(varchar, @qtImpOp)
			END

			--IMPORTA BAIXAS PARA FUNDOS PADRONIZADOS 
			INSERT INTO TB_3040_IMP_OPERACAO (
						CNPJ_FUNDO,
						DT_POSICAO,
						CD_CONTRATO_CEDENTE,
						CD_CONTRATO_SACADO,
						DOC_ORIGINADOR,
						ID_SISTEMA_ORIGEM,
						CD_SISTEMA_ORIGEM,
						TP_ATIVO,
						DS_CONTA_COSIF,
						FL_COOBRIGACAO,
						DT_AQUISICAO,
						DT_VENCIMENTO,
						TX_OPERACAO,
						VL_AQUISICAO,
						VL_NOMINAL,
						VL_PERC_COOBRIGACAO,
						VL_PERC_SUBORDINACAO,
						VL_PDD,
						VL_PERC_INDEXADOR,
						DOC_CEDENTE,
						DOC_SACADO,
						CD_NATUREZA,
						CD_MODALIDADE,
						CD_ORIG_RECURSOS,
						CD_INDEXADOR,
						CD_VAR_CAMB,
						CD_CARAC_ESPEC,
						CD_RATING,
						CD_VINC_ME,
						CD_PRAZO_PROV,
						CD_DESEMPENHO,
						DS_NU_DOCUMENTO,
					    ID_RECEBIVEL,
						ID_ARQUIVO,
						NUM_CONTRATO_C3,
						IC_BAIXAR_ATIVO,  
						IC_RECOMPRA,      
						VL_MOVIMENTACAO,  
						DT_MOVIMENTO,     
						NM_TIPO_MOVIMENTO)
			SELECT  CONVERT(VARCHAR(14), f.NU_CNPJ)					COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
					@dtPosicao								        AS    DT_POSICAO,
					CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
					CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)          COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, 
					CONVERT(VARCHAR(14), o.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
					CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
					'FRT'											COLLATE DATABASE_DEFAULT AS    CD_SISTEMA_ORIGEM,
					CONVERT(VARCHAR(40), t.NM_TIPO_RECEBIVEL)		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
					CONVERT(VARCHAR(100), NULL)						COLLATE DATABASE_DEFAULT AS    DS_CONTA_COSIF,
					CONVERT(BIT, r.IC_COOBRIGACAO)					AS    FL_COOBRIGACAO,
					CONVERT(DATE, r.DT_AQUISICAO)					AS    DT_AQUISICAO, 
					CONVERT(DATE, r.DT_VENCIMENTO)					AS    DT_VENCIMENTO,
					CONVERT(NUMERIC(25,10), ROUND(r.TX_CESSAO, 10)) AS    TX_OPERACAO,
					CONVERT(NUMERIC(19,4), ROUND(r.VL_AQUISICAO,4)) AS    VL_AQUISICAO,                                            
					0	                                        AS    VL_PRESENTE,  
					CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_COOBRIGACAO,
					CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_SUBORDINACAO,
					0		                                    AS    VL_PDD,
					CONVERT(NUMERIC(3,2), ROUND(NULL,2))			AS    VL_PERC_INDEXADOR,
					CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
					CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
					CONVERT(VARCHAR(2), NULL)						AS    CD_NATUREZA, -- ANEXO 02   
					CONVERT(VARCHAR(4), NULL)						AS    CD_MODALIDADE, -- ANEXO 03
					CONVERT(VARCHAR(4), NULL)						AS    CD_ORIG_RECURSOS, -- ANEXO 04
					CONVERT(VARCHAR(2), NULL)						AS    CD_INDEXADOR, -- ANEXO 05
					CONVERT(VARCHAR(3), NULL)						AS    CD_VAR_CAMB, -- ANEXO 06
					CONVERT(VARCHAR(2), NULL)						AS    CD_CARAC_ESPEC, -- ANEXO 08
					CONVERT(VARCHAR(2), NULL)		                COLLATE DATABASE_DEFAULT AS    CD_RATING, -- ANEXO 17 - RATING DO PDD DO CUSTÓDIA --- 
					CONVERT(VARCHAR(1), NULL)						AS    CD_VINC_ME, -- ANEXO 18
					CONVERT(VARCHAR(1), NULL)						AS    CD_PRAZO_PROV, -- ANEXO 19
					CONVERT(VARCHAR(2), NULL)						AS    CD_DESEMPENHO, -- ANEXO 28
					r.DS_NU_DOCUMENTO                               COLLATE DATABASE_DEFAULT AS    DS_NU_DOCUMENTO,
				    m.ID_RECEBIVEL,
					r.ID_ARQUIVO,
					CONVERT(VARCHAR(14), NULL)                      COLLATE DATABASE_DEFAULT AS    NUM_CONTRATO_C3,
					tmm.IC_BAIXAR_ATIVO								AS	  IC_BAIXAR_ATIVO,
					tmm.IC_RECOMPRA                                 AS    IC_RECOMPRA,
					m.VL_MOVIMENTACAO                               AS    VL_MOVIMENTACAO,
					M.DT                                            AS    DT_MOVIMENTO,
					TM.NM_TIPO_MOVIMENTO                            COLLATE DATABASE_DEFAULT AS    NM_TIPO_MOVIMENTO
			FROM          FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO                AS    m    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO                    AS    f    WITH (NOLOCK) ON  (m.ID_FUNDO               =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL                AS    r    WITH (NOLOCK) ON  (r.ID_RECEBIVEL           =    m.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_RECEBIVEL           AS    t    WITH (NOLOCK) ON  (t.ID_TIPO_RECEBIVEL      =    r.ID_TIPO_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE            AS    c    WITH (NOLOCK) ON  (r.ID_CEDENTE             =    c.ID_CEDENTE)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO             AS    s    WITH (NOLOCK) ON  (r.ID_SACADO              =    s.ID_SACADO)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_PESSOA                   AS    o    WITH (NOLOCK) ON  (r.ID_ORIGINADOR          =    o.ID_PESSOA)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
			WHERE          m.DT    between @minDate and @maxDate
			AND            f.NU_CNPJ   =   @cnpjFundo
			AND			   R.VL_AQUISICAO <> 0 
			AND			   R.VL_NOMINAL <> 0   
			AND            TMM.IC_BAIXAR_ATIVO = 1

			UNION ALL

			SELECT  CONVERT(VARCHAR(14), f.NU_CNPJ)					COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
					@dtPosicao								        AS    DT_POSICAO,
					CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
					CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)          COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, 
					CONVERT(VARCHAR(14), o.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
					CONVERT(VARCHAR(100), r.DS_SEU_NUMERO)			COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
					'FRT'											COLLATE DATABASE_DEFAULT AS    CD_SISTEMA_ORIGEM,
					CONVERT(VARCHAR(40), t.NM_TIPO_RECEBIVEL)		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
					CONVERT(VARCHAR(100), NULL)						COLLATE DATABASE_DEFAULT AS    DS_CONTA_COSIF,
					CONVERT(BIT, r.IC_COOBRIGACAO)					AS    FL_COOBRIGACAO,
					CONVERT(DATE, r.DT_AQUISICAO)					AS    DT_AQUISICAO, 
					CONVERT(DATE, r.DT_VENCIMENTO)					AS    DT_VENCIMENTO,
					CONVERT(NUMERIC(25,10), ROUND(r.TX_CESSAO, 10)) AS    TX_OPERACAO,
					CONVERT(NUMERIC(19,4), ROUND(r.VL_AQUISICAO,4)) AS    VL_AQUISICAO,                                            
					0	                                        AS    VL_PRESENTE,  
					CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_COOBRIGACAO,
					CONVERT(NUMERIC(10,7), ROUND(NULL,7))			AS    VL_PERC_SUBORDINACAO,
					0		                                    AS    VL_PDD,
					CONVERT(NUMERIC(3,2), ROUND(NULL,2))			AS    VL_PERC_INDEXADOR,
					CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
					CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
					CONVERT(VARCHAR(2), NULL)						AS    CD_NATUREZA, -- ANEXO 02   
					CONVERT(VARCHAR(4), NULL)						AS    CD_MODALIDADE, -- ANEXO 03
					CONVERT(VARCHAR(4), NULL)						AS    CD_ORIG_RECURSOS, -- ANEXO 04
					CONVERT(VARCHAR(2), NULL)						AS    CD_INDEXADOR, -- ANEXO 05
					CONVERT(VARCHAR(3), NULL)						AS    CD_VAR_CAMB, -- ANEXO 06
					CONVERT(VARCHAR(2), NULL)						AS    CD_CARAC_ESPEC, -- ANEXO 08
					CONVERT(VARCHAR(2), NULL)		                COLLATE DATABASE_DEFAULT AS    CD_RATING, -- ANEXO 17 - RATING DO PDD DO CUSTÓDIA --- 
					CONVERT(VARCHAR(1), NULL)						AS    CD_VINC_ME, -- ANEXO 18
					CONVERT(VARCHAR(1), NULL)						AS    CD_PRAZO_PROV, -- ANEXO 19
					CONVERT(VARCHAR(2), NULL)						AS    CD_DESEMPENHO, -- ANEXO 28
					r.DS_NU_DOCUMENTO                               COLLATE DATABASE_DEFAULT AS    DS_NU_DOCUMENTO,
				    m.ID_RECEBIVEL,
					r.ID_ARQUIVO,
					CONVERT(VARCHAR(14), NULL)                      COLLATE DATABASE_DEFAULT AS    NUM_CONTRATO_C3,
					tmm.IC_BAIXAR_ATIVO								AS	  IC_BAIXAR_ATIVO,
					tmm.IC_RECOMPRA                                 AS    IC_RECOMPRA,
					m.VL_MOVIMENTACAO                               AS    VL_MOVIMENTACAO,
					M.DT                                            AS    DT_MOVIMENTO,
					TM.NM_TIPO_MOVIMENTO                            COLLATE DATABASE_DEFAULT AS    NM_TIPO_MOVIMENTO
			FROM          FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO                AS    m    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO                    AS    f    WITH (NOLOCK) ON  (m.ID_FUNDO               =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL                AS    r    WITH (NOLOCK) ON  (r.ID_RECEBIVEL           =    m.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_RECEBIVEL           AS    t    WITH (NOLOCK) ON  (t.ID_TIPO_RECEBIVEL      =    r.ID_TIPO_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE            AS    c    WITH (NOLOCK) ON  (r.ID_CEDENTE             =    c.ID_CEDENTE)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO             AS    s    WITH (NOLOCK) ON  (r.ID_SACADO              =    s.ID_SACADO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_PESSOA                   AS    o    WITH (NOLOCK) ON  (r.ID_ORIGINADOR          =    o.ID_PESSOA)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
			WHERE          m.DT    between @minDate and @maxDate
			AND            f.NU_CNPJ   =   @cnpjFundo
			AND			   R.VL_AQUISICAO <> 0 
			AND			   R.VL_NOMINAL <> 0   
			AND            TMM.IC_BAIXAR_ATIVO = 1
			
			SET @qtImpOp = @@ROWCOUNT
			SET @dtImpOp = GETDATE()

			IF (@debug = 1)
			BEGIN
				PRINT 'Total de baixas ou liquidações: ' + CONVERT(varchar, @qtImpOp)
			END

			--IMPORTA OS CEDENTES DO CUSTÓDIA (CEDENTES DE AQUISIÇÕES)
			INSERT INTO    TB_3040_IMP_CLIENTE(
						TP_CLIENTE,
						CEP,
						CONG_ECONOMICO,    
						VL_FAT_ANUAL,    
						DT_INI_RELAC,    
						CD_LOCALIZACAO,    
						CD_TP_CONTROLE,    
						CD_TP_PESSOA,
						CD_RATING,    
						CD_AUTORIZACAO,    
						CD_PORTE_PJ,    
						CD_PORTE_PF,
						DOC_CLIENTE,
						NM_CLIENTE,
						IS_SFN
						)
			SELECT        DISTINCT
						'CEDENTE'										 AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		 COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, '')) COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), c.NM_CEDENTE)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END                     AS    IS_SFN
			FROM        FIDC_CUSTODIA_HML.dbo.TB_ESTOQUE             AS    e    WITH (NOLOCK)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_FUNDO               AS    f    WITH (NOLOCK) ON    (e.ID_FUNDO         =    f.ID_FUNDO)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL           AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    e.ID_RECEBIVEL)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE       AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE 
																						   AND   C.ID_FUNDO  =    F.ID_FUNDO) -- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_PORTE                 AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
			LEFT JOIN   FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO           AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
			WHERE        e.DT        =    @dtPosicao
			AND            f.NU_CNPJ    =    @cnpjFundo

			UNION ALL

			SELECT        DISTINCT
						'CEDENTE'										 AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		 COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, '')) COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), c.NM_CEDENTE)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END
																		AS    IS_SFN
			FROM          FIDC_CUSTODIA_HML_2.dbo.TB_ESTOQUE               AS    e    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO               AS    f    WITH (NOLOCK) ON    (e.ID_FUNDO         =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL           AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    e.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE       AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE 
																										AND   C.ID_FUNDO  =    F.ID_FUNDO) -- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_PORTE                 AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
			LEFT JOIN     FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO           AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
			WHERE        e.DT        =    @dtPosicao
			AND            f.NU_CNPJ    =    @cnpjFundo

			SET @qtImpCli = @qtImpCli + @@ROWCOUNT

			 --IMPORTA OS CEDENTES DO CUSTÓDIA (CEDENTES DE BAIXAS)
			INSERT INTO TB_3040_IMP_CLIENTE(
						TP_CLIENTE,
						CEP,
						CONG_ECONOMICO,    
						VL_FAT_ANUAL,    
						DT_INI_RELAC,    
						CD_LOCALIZACAO,    
						CD_TP_CONTROLE,    
						CD_TP_PESSOA,
						CD_RATING,    
						CD_AUTORIZACAO,    
						CD_PORTE_PJ,    
						CD_PORTE_PF,
						DOC_CLIENTE,
						NM_CLIENTE,
						IS_SFN)
			SELECT DISTINCT 'CEDENTE'										 AS    TP_CLIENTE,
						    CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		 COLLATE DATABASE_DEFAULT AS    CEP,
						    CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, '')) COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						    CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
						    												 AS    VL_FAT_ANUAL,
						    CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			 AS    DT_INI_RELAC,
						    CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		 COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						    CONVERT(VARCHAR(2), NULL)						 AS    CD_TP_CONTROLE,	-- ANEXO 10
						    CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
						    						 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
						    						 ELSE NULL
						    					END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
						    CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						    CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						    CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PJ,		-- ANEXO 24
						    CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PF,		-- ANEXO 25
						    CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				    COLLATE DATABASE_DEFAULT  AS    DOC_CLIENTE,
						    CONVERT(VARCHAR(100), c.NM_CEDENTE)				    COLLATE DATABASE_DEFAULT  AS    NM_CLIENTE,
						    CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
			FROM          FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO           AS    m    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO               AS    f    WITH (NOLOCK) ON    (m.ID_FUNDO         =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL           AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    m.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE       AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE 
																									  AND  C.ID_FUNDO  =    F.ID_FUNDO) -- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_PORTE                 AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
			LEFT JOIN   FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO           AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
			WHERE m.DT    between @minDate and @maxDate
			AND   f.NU_CNPJ   =    @cnpjFundo
			AND   TMM.IC_BAIXAR_ATIVO = 1

			UNION ALL

			SELECT DISTINCT 'CEDENTE'										 AS    TP_CLIENTE,
						    CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		 COLLATE DATABASE_DEFAULT AS    CEP,
						    CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, '')) COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						    CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
						    												 AS    VL_FAT_ANUAL,
						    CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			 AS    DT_INI_RELAC,
						    CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		 COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						    CONVERT(VARCHAR(2), NULL)						 AS    CD_TP_CONTROLE,	-- ANEXO 10
						    CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
						    						 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
						    						 ELSE NULL
						    					END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
						    CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						    CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						    CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PJ,		-- ANEXO 24
						    CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PF,		-- ANEXO 25
						    CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				    COLLATE DATABASE_DEFAULT  AS    DOC_CLIENTE,
						    CONVERT(VARCHAR(100), c.NM_CEDENTE)				    COLLATE DATABASE_DEFAULT  AS    NM_CLIENTE,
						    CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
			FROM          FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO           AS    m    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO               AS    f    WITH (NOLOCK) ON    (m.ID_FUNDO         =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL           AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    m.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE       AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE 
																									  AND  C.ID_FUNDO  =    F.ID_FUNDO) -- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN  FIDC_CUSTODIA_HML_2.dbo.TB_PORTE                 AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
			LEFT JOIN   FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO           AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
			INNER JOIN  FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
			INNER JOIN  FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
			WHERE m.DT    between @minDate and @maxDate
			AND   f.NU_CNPJ   =    @cnpjFundo
			AND   TMM.IC_BAIXAR_ATIVO = 1

			SET @qtImpCli = @qtImpCli + @@ROWCOUNT

			--IMPORTA OS SACADOS DO CUSTÓDIA (SACADOS DE AQUISIÇÕES)
			INSERT INTO    TB_3040_IMP_CLIENTE(
						TP_CLIENTE,
						CEP,
						CONG_ECONOMICO,    
						VL_FAT_ANUAL,    
						DT_INI_RELAC,    
						CD_LOCALIZACAO,    
						CD_TP_CONTROLE,    
						CD_TP_PESSOA,
						CD_RATING,    
						CD_AUTORIZACAO,    
						CD_PORTE_PJ,    
						CD_PORTE_PF,
						DOC_CLIENTE,
						NM_CLIENTE,
						IS_SFN
						)
			SELECT        DISTINCT
						'SACADO'										AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, ''))
																		COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			COLLATE DATABASE_DEFAULT AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), s.NM_SACADO)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END
																		AS    IS_SFN
			FROM        FIDC_CUSTODIA_HML.dbo.TB_ESTOQUE               AS  e    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO               AS  f    WITH (NOLOCK)ON    (e.ID_FUNDO                =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL           AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL            =    e.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO        AS  s    WITH (NOLOCK)ON    (r.ID_SACADO            =    s.ID_SACADO 
																										AND   S.ID_FUNDO   =    F.ID_FUNDO)-- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_PORTE                 AS  p    WITH (NOLOCK)ON    (p.ID_PORTE                =    s.ID_PORTE)
			LEFT JOIN  FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO            AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO        =    s.ID_CLASS_RISCO)
			WHERE       e.DT        =    @dtPosicao
			AND         f.NU_CNPJ   =    @cnpjFundo

			UNION ALL

			SELECT        DISTINCT
						'SACADO'										AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, ''))
																		COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			COLLATE DATABASE_DEFAULT AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), s.NM_SACADO)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END
																		AS    IS_SFN
			FROM          FIDC_CUSTODIA_HML_2.dbo.TB_ESTOQUE               AS  e    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO               AS  f    WITH (NOLOCK)ON    (e.ID_FUNDO                =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL           AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL            =    e.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO        AS  s    WITH (NOLOCK)ON    (r.ID_SACADO            =    s.ID_SACADO 
																										AND   S.ID_FUNDO   =    F.ID_FUNDO)-- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_PORTE                 AS  p    WITH (NOLOCK)ON    (p.ID_PORTE                =    s.ID_PORTE)
			LEFT JOIN     FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO            AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO        =    s.ID_CLASS_RISCO)
			WHERE       e.DT        =    @dtPosicao
			AND         f.NU_CNPJ   =    @cnpjFundo

			SET @qtImpCli = @qtImpCli + @@ROWCOUNT

			--IMPORTA OS SACADOS DO CUSTÓDIA (SACADOS DE BAIXAS) 
			INSERT INTO TB_3040_IMP_CLIENTE(
						TP_CLIENTE,
						CEP,
						CONG_ECONOMICO,    
						VL_FAT_ANUAL,    
						DT_INI_RELAC,    
						CD_LOCALIZACAO,    
						CD_TP_CONTROLE,    
						CD_TP_PESSOA,
						CD_RATING,    
						CD_AUTORIZACAO,    
						CD_PORTE_PJ,    
						CD_PORTE_PF,
						DOC_CLIENTE,
						NM_CLIENTE,
						IS_SFN)
			SELECT DISTINCT	'SACADO'										 AS    TP_CLIENTE,
						    CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		 COLLATE DATABASE_DEFAULT AS    CEP,
						    CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, '')) COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						    CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4)) AS    VL_FAT_ANUAL,
						    CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			             AS    DT_INI_RELAC,
						    CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		             COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						    CONVERT(VARCHAR(2), NULL)						             AS    CD_TP_CONTROLE,	-- ANEXO 10
						    CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
						    						 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
						    						 ELSE NULL
						    					END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
						    CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						    CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						    CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PJ,		-- ANEXO 24
						    CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PF,		-- ANEXO 25
						    CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				     COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						    CONVERT(VARCHAR(100), s.NM_SACADO)				     COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						    CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
			FROM          FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO           AS  m    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO               AS  f    WITH (NOLOCK)ON    (m.ID_FUNDO                =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL           AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL            =    m.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO        AS  s    WITH (NOLOCK)ON    (r.ID_SACADO            =    s.ID_SACADO 
																										AND   S.ID_FUNDO   =    F.ID_FUNDO)-- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_PORTE                 AS  p    WITH (NOLOCK)ON    (p.ID_PORTE                =    s.ID_PORTE)
			LEFT JOIN   FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO            AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO        =    s.ID_CLASS_RISCO)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
			INNER JOIN  FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
			WHERE m.DT    between @minDate and @maxDate
			AND   f.NU_CNPJ   =    @cnpjFundo
			AND   TMM.IC_BAIXAR_ATIVO = 1

			UNION ALL

			SELECT DISTINCT	'SACADO'										 AS    TP_CLIENTE,
						    CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		 COLLATE DATABASE_DEFAULT AS    CEP,
						    CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, '')) COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						    CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4)) AS    VL_FAT_ANUAL,
						    CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			             AS    DT_INI_RELAC,
						    CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		             COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						    CONVERT(VARCHAR(2), NULL)						             AS    CD_TP_CONTROLE,	-- ANEXO 10
						    CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
						    						 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
						    						 ELSE NULL
						    					END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
						    CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						    CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						    CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PJ,		-- ANEXO 24
						    CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END) AS    CD_PORTE_PF,		-- ANEXO 25
						    CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				     COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						    CONVERT(VARCHAR(100), s.NM_SACADO)				     COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						    CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
			FROM          FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO           AS  m    WITH (NOLOCK)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO               AS  f    WITH (NOLOCK)ON    (m.ID_FUNDO                =    f.ID_FUNDO)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL           AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL            =    m.ID_RECEBIVEL)
			INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO        AS  s    WITH (NOLOCK)ON    (r.ID_SACADO            =    s.ID_SACADO 
																										AND   S.ID_FUNDO   =    F.ID_FUNDO)-- ADICIONAMOS PARA NÃO DAR DUPLICIDADE NA IMPORTACAO 11-08 HELDER 
			INNER JOIN  FIDC_CUSTODIA_HML_2.dbo.TB_PORTE                 AS  p    WITH (NOLOCK)ON    (p.ID_PORTE                =    s.ID_PORTE)
			LEFT JOIN   FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO            AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO        =    s.ID_CLASS_RISCO)
			INNER JOIN  FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
			INNER JOIN  FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
			WHERE m.DT    between @minDate and @maxDate
			AND   f.NU_CNPJ   =    @cnpjFundo
			AND   TMM.IC_BAIXAR_ATIVO = 1
    
			SET @qtImpCli = @qtImpCli + @@ROWCOUNT
			SET @dtImpCli = GETDATE()

			IF (@debug = 1)
			BEGIN
				PRINT 'Total de clientes: ' + CONVERT(varchar, @qtImpCli)
			END

	END
	ELSE -------------------------------------------------------------------------------------------------------PARA FUNDOS NÃO PADRONIZADOS
	BEGIN

	        --IMPORTA POSIÇÃO DO CUSTÓDIA PARA FUNDOS NÃO PADRONIZADOS - AQUISIÇÕES (ENTRADAS)
			INSERT INTO    TB_3040_IMP_OPERACAO (
						CNPJ_FUNDO,
						DT_POSICAO,
						CD_CONTRATO_CEDENTE,
						CD_CONTRATO_SACADO,
						DOC_ORIGINADOR,
						ID_SISTEMA_ORIGEM,
						CD_SISTEMA_ORIGEM,
						TP_ATIVO,
						DS_CONTA_COSIF,
						FL_COOBRIGACAO,
						DT_AQUISICAO,
						DT_VENCIMENTO,
						TX_OPERACAO,
						VL_AQUISICAO,
						VL_NOMINAL,
						VL_PERC_COOBRIGACAO,
						VL_PERC_SUBORDINACAO,
						VL_PDD,
						VL_PERC_INDEXADOR,
						DOC_CEDENTE,
						DOC_SACADO,
						CD_NATUREZA,
						CD_MODALIDADE,
						CD_ORIG_RECURSOS,
						CD_INDEXADOR,
						CD_VAR_CAMB,
						CD_CARAC_ESPEC,
						CD_RATING,
						CD_VINC_ME,
						CD_PRAZO_PROV,
						CD_DESEMPENHO,
						ID_RECEBIVEL,
						ID_ARQUIVO,
						NUM_CONTRATO_C3,
						IC_BAIXAR_ATIVO,
						IC_RECOMPRA)
		SELECT  CONVERT(VARCHAR(14), f.NU_CNPJ)							COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
				CONVERT(DATE, MAX(e.DT))								AS    DT_POSICAO,
				CONVERT(VARCHAR(100), MAX(r.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
				CONVERT(VARCHAR(100), MAX(r.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, 
				CONVERT(VARCHAR(14),  MAX(o.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
				CONVERT(VARCHAR(100), MAX(r.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
				'FRT'													AS    CD_SISTEMA_ORIGEM,
				CONVERT(VARCHAR(40),(SELECT TOP 1 T.NM_TIPO_RECEBIVEL FROM FIDC_CUSTODIA_HML.dbo.TB_TIPO_RECEBIVEL AS T))   
																		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
				CONVERT(VARCHAR(100), NULL)								AS    DS_CONTA_COSIF,
				CONVERT(BIT, r.IC_COOBRIGACAO)						    AS    FL_COOBRIGACAO,
				CONVERT(DATE, MAX(r.DT_AQUISICAO))						AS    DT_AQUISICAO, 
			   CONVERT(DATE, MAX(E.DT) + '19050624')					AS    DT_VENCIMENTO,
				CONVERT(NUMERIC(25,10), MAX(ROUND(r.TX_CESSAO, 10)))    AS    TX_OPERACAO,	
				SUM (r.VL_AQUISICAO)									AS    VL_AQUISICAO,                                           
				CONVERT(NUMERIC(19,4), ROUND(SUM(E.VL_PRESENTE),4))		AS    VL_NOMINAL,
				'100'													AS    VL_PERC_COOBRIGACAO,	
				CONVERT(NUMERIC(10,7), ROUND(NULL,7))					AS    VL_PERC_SUBORDINACAO,
				CONVERT(NUMERIC(19,4), ROUND(SUM(e.VL_PDD),4))			AS    VL_PDD,
				CONVERT(NUMERIC(3,2), ROUND(NULL,2))					AS    VL_PERC_INDEXADOR,
				CONVERT(VARCHAR(14), MAX(C.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
				CONVERT(VARCHAR(14), MAX(S.NU_CPF_CNPJ))	            COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
				CONVERT(VARCHAR(2), NULL)								AS    CD_NATUREZA, -- ANEXO 02   
				CONVERT(VARCHAR(4), NULL)								AS    CD_MODALIDADE, -- ANEXO 03
				CONVERT(VARCHAR(4), NULL)								AS    CD_ORIG_RECURSOS, -- ANEXO 04
				CONVERT(VARCHAR(2), NULL)								AS    CD_INDEXADOR, -- ANEXO 05
				CONVERT(VARCHAR(3), NULL)								AS    CD_VAR_CAMB, -- ANEXO 06
				CONVERT(VARCHAR(2), NULL)								AS    CD_CARAC_ESPEC, -- ANEXO 08
				CONVERT(VARCHAR(2), NULL)								AS    CD_RATING, -- ANEXO 17
				CONVERT(VARCHAR(1), NULL)								AS    CD_VINC_ME, -- ANEXO 18
				CONVERT(VARCHAR(1), NULL)								AS    CD_PRAZO_PROV, -- ANEXO 19
				CONVERT(VARCHAR(2), NULL)								AS    CD_DESEMPENHO, -- ANEXO 28
				E.ID_RECEBIVEL,
				r.ID_ARQUIVO,
				CONVERT(VARCHAR(14), MAX(R.NUM_CONTRATO_C3))            AS    NUM_CONTRATO_C3,
				0                                                       AS    IC_BAIXAR_ATIVO,
				0                                                       AS    IC_RECOMPRA
		FROM          FIDC_CUSTODIA_HML.dbo.TB_ESTOQUE            AS    e    WITH (NOLOCK)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO              AS    f    WITH (NOLOCK) ON  (e.ID_FUNDO             =    f.ID_FUNDO)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL          AS    r    WITH (NOLOCK) ON  (r.ID_RECEBIVEL         =    e.ID_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_RECEBIVEL     AS    t    WITH (NOLOCK) ON  (t.ID_TIPO_RECEBIVEL    =    r.ID_TIPO_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE      AS    c    WITH (NOLOCK) ON  (r.ID_CEDENTE           =    c.ID_CEDENTE)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO       AS    s    WITH (NOLOCK) ON  (r.ID_SACADO            =    s.ID_SACADO)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_PESSOA             AS    o    WITH (NOLOCK) ON  (r.ID_ORIGINADOR        =    o.ID_PESSOA)
		INNER JOIN	  FIDC_CUSTODIA_HML.dbo.TB_FAIXA_PDD	       AS    fp   WITH (NOLOCK) ON  (e.ID_FAIXA_PDD = fp.ID_FAIXA_PDD)
		WHERE          e.DT        =    @dtPosicao
		AND            f.NU_CNPJ   =    @cnpjFundo
		AND			   R.VL_AQUISICAO <> 0 -- TESTE DIOGO
		AND			   R.VL_NOMINAL <> 0   -- TESTE DIOGO
		GROUP BY f.NU_CNPJ,
	             r.ID_ARQUIVO,
				 r.IC_COOBRIGACAO,
				 e.DT,
				 E.ID_RECEBIVEL

        UNION ALL

       SELECT  CONVERT(VARCHAR(14), f.NU_CNPJ)							COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
				CONVERT(DATE, MAX(e.DT))								AS    DT_POSICAO,
				CONVERT(VARCHAR(100), MAX(r.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
				CONVERT(VARCHAR(100), MAX(r.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, 
				CONVERT(VARCHAR(14),  MAX(o.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
				CONVERT(VARCHAR(100), MAX(r.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
				'FRT'													AS    CD_SISTEMA_ORIGEM,
				CONVERT(VARCHAR(40),(SELECT TOP 1 T.NM_TIPO_RECEBIVEL 
				                     FROM FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_RECEBIVEL AS T))   
																		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
				CONVERT(VARCHAR(100), NULL)								AS    DS_CONTA_COSIF,
				CONVERT(BIT, r.IC_COOBRIGACAO)						    AS    FL_COOBRIGACAO,
				CONVERT(DATE, MAX(r.DT_AQUISICAO))						AS    DT_AQUISICAO, 
			   CONVERT(DATE, MAX(E.DT) + '19050624')					AS    DT_VENCIMENTO,
				CONVERT(NUMERIC(25,10), MAX(ROUND(r.TX_CESSAO, 10)))    AS    TX_OPERACAO,	
				SUM (r.VL_AQUISICAO)									AS    VL_AQUISICAO,                                           
				CONVERT(NUMERIC(19,4), ROUND(SUM(E.VL_PRESENTE),4))		AS    VL_NOMINAL,
				'100'													AS    VL_PERC_COOBRIGACAO,	
				CONVERT(NUMERIC(10,7), ROUND(NULL,7))					AS    VL_PERC_SUBORDINACAO,
				CONVERT(NUMERIC(19,4), ROUND(SUM(e.VL_PDD),4))			AS    VL_PDD,
				CONVERT(NUMERIC(3,2), ROUND(NULL,2))					AS    VL_PERC_INDEXADOR,
				CONVERT(VARCHAR(14), MAX(C.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
				CONVERT(VARCHAR(14), MAX(S.NU_CPF_CNPJ))	            COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
				CONVERT(VARCHAR(2), NULL)								AS    CD_NATUREZA, -- ANEXO 02   
				CONVERT(VARCHAR(4), NULL)								AS    CD_MODALIDADE, -- ANEXO 03
				CONVERT(VARCHAR(4), NULL)								AS    CD_ORIG_RECURSOS, -- ANEXO 04
				CONVERT(VARCHAR(2), NULL)								AS    CD_INDEXADOR, -- ANEXO 05
				CONVERT(VARCHAR(3), NULL)								AS    CD_VAR_CAMB, -- ANEXO 06
				CONVERT(VARCHAR(2), NULL)								AS    CD_CARAC_ESPEC, -- ANEXO 08
				CONVERT(VARCHAR(2), NULL)								AS    CD_RATING, -- ANEXO 17
				CONVERT(VARCHAR(1), NULL)								AS    CD_VINC_ME, -- ANEXO 18
				CONVERT(VARCHAR(1), NULL)								AS    CD_PRAZO_PROV, -- ANEXO 19
				CONVERT(VARCHAR(2), NULL)								AS    CD_DESEMPENHO, -- ANEXO 28
				E.ID_RECEBIVEL,
				r.ID_ARQUIVO,
				CONVERT(VARCHAR(14), MAX(R.NUM_CONTRATO_C3))            AS    NUM_CONTRATO_C3,
				0                                                       AS    IC_BAIXAR_ATIVO,
				0                                                       AS    IC_RECOMPRA
		FROM          FIDC_CUSTODIA_HML_2.dbo.TB_ESTOQUE            AS    e    WITH (NOLOCK)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO              AS    f    WITH (NOLOCK) ON  (e.ID_FUNDO             =    f.ID_FUNDO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL          AS    r    WITH (NOLOCK) ON  (r.ID_RECEBIVEL         =    e.ID_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_RECEBIVEL     AS    t    WITH (NOLOCK) ON  (t.ID_TIPO_RECEBIVEL    =    r.ID_TIPO_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE      AS    c    WITH (NOLOCK) ON  (r.ID_CEDENTE           =    c.ID_CEDENTE)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO       AS    s    WITH (NOLOCK) ON  (r.ID_SACADO            =    s.ID_SACADO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_PESSOA             AS    o    WITH (NOLOCK) ON  (r.ID_ORIGINADOR        =    o.ID_PESSOA)
		INNER JOIN	  FIDC_CUSTODIA_HML_2.dbo.TB_FAIXA_PDD	       AS    fp   WITH (NOLOCK) ON  (e.ID_FAIXA_PDD = fp.ID_FAIXA_PDD)
		WHERE          e.DT        =    @dtPosicao
		AND            f.NU_CNPJ   =    @cnpjFundo
		AND			   R.VL_AQUISICAO <> 0 -- TESTE DIOGO
		AND			   R.VL_NOMINAL <> 0   -- TESTE DIOGO
		GROUP BY f.NU_CNPJ,
	             r.ID_ARQUIVO,
				 r.IC_COOBRIGACAO,
				 e.DT,
				 E.ID_RECEBIVEL

		SET @qtImpOp = @@ROWCOUNT
		SET @dtImpOp = GETDATE()

		IF (@debug = 1)
		BEGIN
			PRINT 'Total de operações: ' + CONVERT(varchar, @qtImpOp)
		END

		--IMPORTA POSIÇÃO DO CUSTÓDIA PARA FUNDOS NÃO PADRONIZADOS - BAIXAS (SAIDAS)
		INSERT INTO    TB_3040_IMP_OPERACAO (
						CNPJ_FUNDO,
						DT_POSICAO,
						CD_CONTRATO_CEDENTE,
						CD_CONTRATO_SACADO,
						DOC_ORIGINADOR,
						ID_SISTEMA_ORIGEM,
						CD_SISTEMA_ORIGEM,
						TP_ATIVO,
						DS_CONTA_COSIF,
						FL_COOBRIGACAO,
						DT_AQUISICAO,
						DT_VENCIMENTO,
						TX_OPERACAO,
						VL_AQUISICAO,
						VL_NOMINAL,
						VL_PERC_COOBRIGACAO,
						VL_PERC_SUBORDINACAO,
						VL_PDD,
						VL_PERC_INDEXADOR,
						DOC_CEDENTE,
						DOC_SACADO,
						CD_NATUREZA,
						CD_MODALIDADE,
						CD_ORIG_RECURSOS,
						CD_INDEXADOR,
						CD_VAR_CAMB,
						CD_CARAC_ESPEC,
						CD_RATING,
						CD_VINC_ME,
						CD_PRAZO_PROV,
						CD_DESEMPENHO,
						NUM_CONTRATO_C3,
						IC_BAIXAR_ATIVO,  
						IC_RECOMPRA,      
						VL_MOVIMENTACAO,  
						DT_MOVIMENTO,     
						NM_TIPO_MOVIMENTO)
		SELECT  CONVERT(VARCHAR(14), F.NU_CNPJ)							COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
				CONVERT(DATE, MAX(@DTPOSICAO))							AS    DT_POSICAO,
				CONVERT(VARCHAR(100), MAX(R.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
				CONVERT(VARCHAR(100), MAX(R.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, 
				CONVERT(VARCHAR(14),  MAX(O.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
				CONVERT(VARCHAR(100), MAX(R.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
				'FRT'													AS    CD_SISTEMA_ORIGEM,
				CONVERT(VARCHAR(40),(SELECT TOP 1 T.NM_TIPO_RECEBIVEL FROM FIDC_CUSTODIA_HML.DBO.TB_TIPO_RECEBIVEL AS T))   
																		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
				CONVERT(VARCHAR(100), NULL)								AS    DS_CONTA_COSIF,
				CONVERT(BIT, R.IC_COOBRIGACAO)						    AS    FL_COOBRIGACAO,
				CONVERT(DATE, MAX(R.DT_AQUISICAO))						AS    DT_AQUISICAO, 
		   	    CONVERT(DATE, MAX(@DTPOSICAO) + '19050624')				AS    DT_VENCIMENTO,
			    CONVERT(NUMERIC(25,10), MAX(ROUND(R.TX_CESSAO, 10)))    AS    TX_OPERACAO,	
				SUM (R.VL_AQUISICAO)									AS    VL_AQUISICAO,                                           
				0                                               		AS    VL_NOMINAL,
				'100'													AS    VL_PERC_COOBRIGACAO,	
	        	CONVERT(NUMERIC(10,7), ROUND(NULL,7))					AS    VL_PERC_SUBORDINACAO,
				0			                                            AS    VL_PDD,
				CONVERT(NUMERIC(3,2), ROUND(NULL,2))					AS    VL_PERC_INDEXADOR,
				CONVERT(VARCHAR(14), MAX(C.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
				CONVERT(VARCHAR(14), MAX(S.NU_CPF_CNPJ))	            COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
				CONVERT(VARCHAR(2), NULL)								AS    CD_NATUREZA, -- ANEXO 02   
				CONVERT(VARCHAR(4), NULL)								AS    CD_MODALIDADE, -- ANEXO 03
				CONVERT(VARCHAR(4), NULL)								AS    CD_ORIG_RECURSOS, -- ANEXO 04
				CONVERT(VARCHAR(2), NULL)								AS    CD_INDEXADOR, -- ANEXO 05
				CONVERT(VARCHAR(3), NULL)								AS    CD_VAR_CAMB, -- ANEXO 06
				CONVERT(VARCHAR(2), NULL)								AS    CD_CARAC_ESPEC, -- ANEXO 08
				CONVERT(VARCHAR(2), NULL)								COLLATE DATABASE_DEFAULT AS    CD_RATING, -- ANEXO 17
				CONVERT(VARCHAR(1), NULL)								AS    CD_VINC_ME, -- ANEXO 18
				CONVERT(VARCHAR(1), NULL)								AS    CD_PRAZO_PROV, -- ANEXO 19
				CONVERT(VARCHAR(2), NULL)								AS    CD_DESEMPENHO, -- ANEXO 28
				CONVERT(VARCHAR(14), MAX(R.NUM_CONTRATO_C3))            COLLATE DATABASE_DEFAULT AS    NUM_CONTRATO_C3,
			    TMM.IC_BAIXAR_ATIVO								        AS	  IC_BAIXAR_ATIVO,
			    TMM.IC_RECOMPRA                                         AS    IC_RECOMPRA,
			    SUM(M.VL_MOVIMENTACAO)                                  AS    VL_MOVIMENTACAO,
			    M.DT                                                    AS    DT_MOVIMENTO,
			    TM.NM_TIPO_MOVIMENTO                                    COLLATE DATABASE_DEFAULT AS    NM_TIPO_MOVIMENTO
		FROM          FIDC_CUSTODIA_HML.DBO.TB_MOVIMENTO          AS    M    WITH (NOLOCK)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_FUNDO              AS    F    WITH (NOLOCK) ON  (M.ID_FUNDO             =    F.ID_FUNDO)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_RECEBIVEL          AS    R    WITH (NOLOCK) ON  (R.ID_RECEBIVEL         =    M.ID_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_TIPO_RECEBIVEL     AS    T    WITH (NOLOCK) ON  (T.ID_TIPO_RECEBIVEL    =    R.ID_TIPO_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_FUNDO_CEDENTE      AS    C    WITH (NOLOCK) ON  (R.ID_CEDENTE           =    C.ID_CEDENTE)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_FUNDO_SACADO       AS    S    WITH (NOLOCK) ON  (R.ID_SACADO            =    S.ID_SACADO)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_PESSOA             AS    O    WITH (NOLOCK) ON  (R.ID_ORIGINADOR        =    O.ID_PESSOA)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_TIPO_MOVIMENTO     AS    TM   WITH (NOLOCK) ON  (TM.ID_TIPO_MOVIMENTO     =    M.ID_TIPO_MOVIMENTO)
		INNER JOIN    FIDC_CUSTODIA_HML.DBO.TB_TIPO_MOVIMENTACAO  AS    TMM  WITH (NOLOCK) ON  (TMM.CD_TIPO_MOVIMENTACAO =    TM.CD_TIPO_MOVIMENTACAO)	
		WHERE          M.DT    BETWEEN @MINDATE AND @MAXDATE
		AND            F.NU_CNPJ   =   @CNPJFUNDO
		AND			   R.VL_AQUISICAO <> 0 
		AND			   R.VL_NOMINAL <> 0   
		AND            TMM.IC_BAIXAR_ATIVO = 1
		GROUP BY F.NU_CNPJ,
	             R.ID_ARQUIVO,
				 R.IC_COOBRIGACAO,
				 TMM.IC_BAIXAR_ATIVO,	
				 TMM.IC_RECOMPRA,       
				 M.DT,                  
				 TM.NM_TIPO_MOVIMENTO  
				 
		UNION ALL
		
		SELECT  CONVERT(VARCHAR(14), F.NU_CNPJ)							COLLATE DATABASE_DEFAULT AS    CNPJ_FUNDO,
				CONVERT(DATE, MAX(@DTPOSICAO))							AS    DT_POSICAO,
				CONVERT(VARCHAR(100), MAX(R.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_CEDENTE, 
				CONVERT(VARCHAR(100), MAX(R.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    CD_CONTRATO_SACADO, 
				CONVERT(VARCHAR(14),  MAX(O.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_ORIGINADOR,
				CONVERT(VARCHAR(100), MAX(R.DS_SEU_NUMERO))				COLLATE DATABASE_DEFAULT AS    ID_SISTEMA_ORIGEM,
				'FRT'													AS    CD_SISTEMA_ORIGEM,
				CONVERT(VARCHAR(40),(SELECT TOP 1 T.NM_TIPO_RECEBIVEL FROM FIDC_CUSTODIA_HML_2.DBO.TB_TIPO_RECEBIVEL AS T))   
																		COLLATE DATABASE_DEFAULT AS    TP_ATIVO,
				CONVERT(VARCHAR(100), NULL)								AS    DS_CONTA_COSIF,
				CONVERT(BIT, R.IC_COOBRIGACAO)						    AS    FL_COOBRIGACAO,
				CONVERT(DATE, MAX(R.DT_AQUISICAO))						AS    DT_AQUISICAO, 
		   	    CONVERT(DATE, MAX(@DTPOSICAO) + '19050624')				AS    DT_VENCIMENTO,
			    CONVERT(NUMERIC(25,10), MAX(ROUND(R.TX_CESSAO, 10)))    AS    TX_OPERACAO,	
				SUM (R.VL_AQUISICAO)									AS    VL_AQUISICAO,                                           
				0                                               		AS    VL_NOMINAL,
				'100'													AS    VL_PERC_COOBRIGACAO,	
	        	CONVERT(NUMERIC(10,7), ROUND(NULL,7))					AS    VL_PERC_SUBORDINACAO,
				0			                                            AS    VL_PDD,
				CONVERT(NUMERIC(3,2), ROUND(NULL,2))					AS    VL_PERC_INDEXADOR,
				CONVERT(VARCHAR(14), MAX(C.NU_CPF_CNPJ))				COLLATE DATABASE_DEFAULT AS    DOC_CEDENTE,
				CONVERT(VARCHAR(14), MAX(S.NU_CPF_CNPJ))	            COLLATE DATABASE_DEFAULT AS    DOC_SACADO,
				CONVERT(VARCHAR(2), NULL)								AS    CD_NATUREZA, -- ANEXO 02   
				CONVERT(VARCHAR(4), NULL)								AS    CD_MODALIDADE, -- ANEXO 03
				CONVERT(VARCHAR(4), NULL)								AS    CD_ORIG_RECURSOS, -- ANEXO 04
				CONVERT(VARCHAR(2), NULL)								AS    CD_INDEXADOR, -- ANEXO 05
				CONVERT(VARCHAR(3), NULL)								AS    CD_VAR_CAMB, -- ANEXO 06
				CONVERT(VARCHAR(2), NULL)								AS    CD_CARAC_ESPEC, -- ANEXO 08
				CONVERT(VARCHAR(2), NULL)								COLLATE DATABASE_DEFAULT AS    CD_RATING, -- ANEXO 17
				CONVERT(VARCHAR(1), NULL)								AS    CD_VINC_ME, -- ANEXO 18
				CONVERT(VARCHAR(1), NULL)								AS    CD_PRAZO_PROV, -- ANEXO 19
				CONVERT(VARCHAR(2), NULL)								AS    CD_DESEMPENHO, -- ANEXO 28
				CONVERT(VARCHAR(14), MAX(R.NUM_CONTRATO_C3))            COLLATE DATABASE_DEFAULT AS    NUM_CONTRATO_C3,
			    TMM.IC_BAIXAR_ATIVO								        AS	  IC_BAIXAR_ATIVO,
			    TMM.IC_RECOMPRA                                         AS    IC_RECOMPRA,
			    SUM(M.VL_MOVIMENTACAO)                                  AS    VL_MOVIMENTACAO,
			    M.DT                                                    AS    DT_MOVIMENTO,
			    TM.NM_TIPO_MOVIMENTO                                    COLLATE DATABASE_DEFAULT AS    NM_TIPO_MOVIMENTO
		FROM          FIDC_CUSTODIA_HML_2.DBO.TB_MOVIMENTO          AS    M    WITH (NOLOCK)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_FUNDO              AS    F    WITH (NOLOCK) ON  (M.ID_FUNDO             =    F.ID_FUNDO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_RECEBIVEL          AS    R    WITH (NOLOCK) ON  (R.ID_RECEBIVEL         =    M.ID_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_TIPO_RECEBIVEL     AS    T    WITH (NOLOCK) ON  (T.ID_TIPO_RECEBIVEL    =    R.ID_TIPO_RECEBIVEL)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_FUNDO_CEDENTE      AS    C    WITH (NOLOCK) ON  (R.ID_CEDENTE           =    C.ID_CEDENTE)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_FUNDO_SACADO       AS    S    WITH (NOLOCK) ON  (R.ID_SACADO            =    S.ID_SACADO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_PESSOA             AS    O    WITH (NOLOCK) ON  (R.ID_ORIGINADOR        =    O.ID_PESSOA)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_TIPO_MOVIMENTO     AS    TM   WITH (NOLOCK) ON  (TM.ID_TIPO_MOVIMENTO     =    M.ID_TIPO_MOVIMENTO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.DBO.TB_TIPO_MOVIMENTACAO  AS    TMM  WITH (NOLOCK) ON  (TMM.CD_TIPO_MOVIMENTACAO =    TM.CD_TIPO_MOVIMENTACAO)	
		WHERE          M.DT    BETWEEN @MINDATE AND @MAXDATE
		AND            F.NU_CNPJ   =   @CNPJFUNDO
		AND			   R.VL_AQUISICAO <> 0 
		AND			   R.VL_NOMINAL <> 0   
		AND            TMM.IC_BAIXAR_ATIVO = 1
		GROUP BY F.NU_CNPJ,
	             R.ID_ARQUIVO,
				 R.IC_COOBRIGACAO,
				 TMM.IC_BAIXAR_ATIVO,	
				 TMM.IC_RECOMPRA,       
				 M.DT,                  
				 TM.NM_TIPO_MOVIMENTO  		 
				 
		
		SET @qtImpOp = @@ROWCOUNT
		SET @dtImpOp = GETDATE()

		IF (@debug = 1)
		BEGIN
			PRINT 'Total de baixas ou liquidações: ' + CONVERT(varchar, @qtImpOp)
		END
		
			--IMPORTA OS CEDENTES DO CUSTÓDIA NAO PADROINIZADOS (CEDENTES DE AQUISIÇÕES) 
			INSERT INTO    TB_3040_IMP_CLIENTE(
						TP_CLIENTE,
						CEP,
						CONG_ECONOMICO,    
						VL_FAT_ANUAL,    
						DT_INI_RELAC,    
						CD_LOCALIZACAO,    
						CD_TP_CONTROLE,    
						CD_TP_PESSOA,
						CD_RATING,    
						CD_AUTORIZACAO,    
						CD_PORTE_PJ,    
						CD_PORTE_PF,
						DOC_CLIENTE,
						NM_CLIENTE,
						IS_SFN
						)
			--SELECT	CEDENTE.*
			--FROM	(
			SELECT        DISTINCT
						'CEDENTE'										AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, ''))
																		COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), c.NM_CEDENTE)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
								CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS IS_SFN
				FROM			FIDC_CUSTODIA_HML.dbo.TB_ESTOQUE          AS    e    WITH (NOLOCK)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO            AS    f    WITH (NOLOCK) ON    (e.ID_FUNDO         =    f.ID_FUNDO)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL        AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    e.ID_RECEBIVEL)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE    AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE  
																											   AND C.ID_FUNDO = F.ID_FUNDO)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_PORTE            AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
				LEFT JOIN		FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO      AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
			WHERE        e.DT        =    @dtPosicao
			AND          f.NU_CNPJ   =    @cnpjFundo
				--	) AS CEDENTE
		  --  INNER JOIN		TB_3040_IMP_OPERACAO AS IMP
			 --ON				IMP.DOC_SACADO = CEDENTE.DOC_CLIENTE

			 UNION ALL

			SELECT        DISTINCT
						'CEDENTE'										AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, ''))
																		COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), c.NM_CEDENTE)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
								CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS IS_SFN
			 FROM			FIDC_CUSTODIA_HML_2.dbo.TB_ESTOQUE          AS    e    WITH (NOLOCK)
			 INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO            AS    f    WITH (NOLOCK) ON    (e.ID_FUNDO         =    f.ID_FUNDO)
			 INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL        AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    e.ID_RECEBIVEL)
			 INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE    AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE  
			 																								AND C.ID_FUNDO = F.ID_FUNDO)
			 INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_PORTE            AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
			 LEFT JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO      AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
			 WHERE        e.DT        =    @dtPosicao
			 AND          f.NU_CNPJ   =    @cnpjFundo
				--	) AS CEDENTE
		  --  INNER JOIN		TB_3040_IMP_OPERACAO AS IMP
			 --ON				IMP.DOC_SACADO = CEDENTE.DOC_CLIENTE

			SET @qtImpCli = @qtImpCli + @@ROWCOUNT

		--IMPORTA OS CEDENTES DO CUSTÓDIA NAO PADROINIZADOS (CEDENTES DE BAIXAS)
		INSERT INTO    TB_3040_IMP_CLIENTE(
					TP_CLIENTE,
					CEP,
					CONG_ECONOMICO,    
					VL_FAT_ANUAL,    
					DT_INI_RELAC,    
					CD_LOCALIZACAO,    
					CD_TP_CONTROLE,    
					CD_TP_PESSOA,
					CD_RATING,    
					CD_AUTORIZACAO,    
					CD_PORTE_PJ,    
					CD_PORTE_PF,
					DOC_CLIENTE,
					NM_CLIENTE,
					IS_SFN)
		SELECT        DISTINCT
					'CEDENTE'										AS    TP_CLIENTE,
					CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
					CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, ''))
																	COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
					CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
																	AS    VL_FAT_ANUAL,
					CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
					CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
					CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
					CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
											 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
											 ELSE NULL
										END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
					CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
					CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
					CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																	AS    CD_PORTE_PJ,		-- ANEXO 24
					CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																	AS    CD_PORTE_PF,		-- ANEXO 25
					CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
					CONVERT(VARCHAR(100), c.NM_CEDENTE)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
							CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS IS_SFN
		FROM			FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO        AS    m    WITH (NOLOCK)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO            AS    f    WITH (NOLOCK) ON    (m.ID_FUNDO         =    f.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL        AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    m.ID_RECEBIVEL)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO_CEDENTE    AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE  
																									   AND C.ID_FUNDO = F.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_PORTE            AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
		LEFT JOIN		FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO      AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
		INNER JOIN    FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
		WHERE m.DT    between @minDate and @maxDate
		AND   f.NU_CNPJ   =    @cnpjFundo
		AND   TMM.IC_BAIXAR_ATIVO = 1
		
		UNION ALL
		
		SELECT        DISTINCT
					'CEDENTE'										AS    TP_CLIENTE,
					CONVERT(VARCHAR(8), NULLIF(c.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
					CONVERT(VARCHAR(40), NULLIF(c.NM_CONG_ECON, ''))
																	COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
					CONVERT(NUMERIC(19,4), ROUND(NULLIF(c.VL_FAT_ANUAL, 0.0),4))
																	AS    VL_FAT_ANUAL,
					CONVERT(DATE, c.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
					CONVERT(VARCHAR(2), NULLIF(c.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
					CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
					CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN '1' 
											 WHEN c.IC_TIPO_PESSOA = 1 THEN '2'
											 ELSE NULL
										END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
					CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
					CONVERT(VARCHAR(1), c.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
					CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																	AS    CD_PORTE_PJ,		-- ANEXO 24
					CONVERT(VARCHAR(1), CASE WHEN c.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																	AS    CD_PORTE_PF,		-- ANEXO 25
					CONVERT(VARCHAR(14), c.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
					CONVERT(VARCHAR(100), c.NM_CEDENTE)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
							CASE WHEN c.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS IS_SFN
		FROM			FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO        AS    m    WITH (NOLOCK)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO            AS    f    WITH (NOLOCK) ON    (m.ID_FUNDO         =    f.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL        AS    r    WITH (NOLOCK) ON    (r.ID_RECEBIVEL     =    m.ID_RECEBIVEL)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_CEDENTE    AS    c    WITH (NOLOCK) ON    (r.ID_CEDENTE       =    c.ID_CEDENTE  
																									   AND C.ID_FUNDO = F.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_PORTE            AS    p    WITH (NOLOCK) ON    (p.ID_PORTE         =    c.ID_PORTE)
		LEFT JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO      AS    cl   WITH (NOLOCK) ON    (cl.ID_CLASS_RISCO  =    c.ID_CLASS_RISCO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTO           AS    tm   WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
		INNER JOIN    FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTACAO        AS    tmm  WITH (NOLOCK) ON  (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
		WHERE m.DT    between @minDate and @maxDate
		AND   f.NU_CNPJ   =    @cnpjFundo
		AND   TMM.IC_BAIXAR_ATIVO = 1
		
			SET @qtImpCli = @qtImpCli + @@ROWCOUNT


		--IMPORTA OS SACADOS DO CUSTÓDIA NAO PADRONIZADOS (SACADOS DE AQUISIÇÕES)
			INSERT INTO    TB_3040_IMP_CLIENTE(
						TP_CLIENTE,
						CEP,
						CONG_ECONOMICO,    
						VL_FAT_ANUAL,    
						DT_INI_RELAC,    
						CD_LOCALIZACAO,    
						CD_TP_CONTROLE,    
						CD_TP_PESSOA,
						CD_RATING,    
						CD_AUTORIZACAO,    
						CD_PORTE_PJ,    
						CD_PORTE_PF,
						DOC_CLIENTE,
						NM_CLIENTE,
						IS_SFN
						)
			--SELECT	SACADO.*
			--FROM	(
			SELECT        DISTINCT
						'SACADO'										AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, ''))
																		COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), s.NM_SACADO)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
								CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
				FROM			FIDC_CUSTODIA_HML.dbo.TB_ESTOQUE        AS  e    WITH (NOLOCK)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO          AS  f    WITH (NOLOCK)ON    (e.ID_FUNDO        =    f.ID_FUNDO)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL      AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL    =    e.ID_RECEBIVEL)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO   AS  s    WITH (NOLOCK)ON    (r.ID_SACADO       =    s.ID_SACADO  AND S.ID_FUNDO = F.ID_FUNDO)
				INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_PORTE          AS  p    WITH (NOLOCK)ON    (p.ID_PORTE        =    s.ID_PORTE)
				LEFT JOIN		FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO    AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO =    s.ID_CLASS_RISCO)
			WHERE        e.DT        =    @dtPosicao
			AND          f.NU_CNPJ   =    @cnpjFundo
		 	   --      ) AS SACADO
			    --INNER JOIN	TB_3040_IMP_OPERACAO AS IMP
			    -- ON			IMP.DOC_SACADO = SACADO.DOC_CLIENTE

			UNION ALL

			SELECT        DISTINCT
						'SACADO'										AS    TP_CLIENTE,
						CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
						CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, ''))
																		COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
						CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4))
																		AS    VL_FAT_ANUAL,
						CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
						CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
						CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
												 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
												 ELSE NULL
											END)						AS    CD_TP_PESSOA,		-- ANEXO 11
						CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
						CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PJ,		-- ANEXO 24
						CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																		AS    CD_PORTE_PF,		-- ANEXO 25
						CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
						CONVERT(VARCHAR(100), s.NM_SACADO)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
								CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
				FROM			FIDC_CUSTODIA_HML_2.dbo.TB_ESTOQUE        AS  e    WITH (NOLOCK)
				INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO          AS  f    WITH (NOLOCK)ON    (e.ID_FUNDO        =    f.ID_FUNDO)
				INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL      AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL    =    e.ID_RECEBIVEL)
				INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO   AS  s    WITH (NOLOCK)ON    (r.ID_SACADO       =    s.ID_SACADO  AND S.ID_FUNDO = F.ID_FUNDO)
				INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_PORTE          AS  p    WITH (NOLOCK)ON    (p.ID_PORTE        =    s.ID_PORTE)
				LEFT JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO    AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO =    s.ID_CLASS_RISCO)
			WHERE        e.DT        =    @dtPosicao
			AND          f.NU_CNPJ   =    @cnpjFundo
		 	   --      ) AS SACADO
			    --INNER JOIN	TB_3040_IMP_OPERACAO AS IMP
			    -- ON			IMP.DOC_SACADO = SACADO.DOC_CLIENTE
    
    
    	SET @qtImpCli = @qtImpCli + @@ROWCOUNT
    
		--IMPORTA OS SACADOS DO CUSTÓDIA NAO PADRONIZADOS (SACADOS DE BAIXAS) 
		INSERT INTO    TB_3040_IMP_CLIENTE(
					TP_CLIENTE,
					CEP,
					CONG_ECONOMICO,    
					VL_FAT_ANUAL,    
					DT_INI_RELAC,    
					CD_LOCALIZACAO,    
					CD_TP_CONTROLE,    
					CD_TP_PESSOA,
					CD_RATING,    
					CD_AUTORIZACAO,    
					CD_PORTE_PJ,    
					CD_PORTE_PF,
					DOC_CLIENTE,
					NM_CLIENTE,
					IS_SFN)
		SELECT        DISTINCT
				'SACADO'										AS    TP_CLIENTE,
				CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
				CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, ''))
																COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
				CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4))
																AS    VL_FAT_ANUAL,
				CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
				CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
				CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
				CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
										 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
										 ELSE NULL
									END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
				CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
				CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
				CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																AS    CD_PORTE_PJ,		-- ANEXO 24
				CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																AS    CD_PORTE_PF,		-- ANEXO 25
				CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
				CONVERT(VARCHAR(100), s.NM_SACADO)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
		FROM			FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO         AS  m    WITH (NOLOCK)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO             AS  f    WITH (NOLOCK)ON    (m.ID_FUNDO        =    f.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL         AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL    =    m.ID_RECEBIVEL)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_FUNDO_SACADO      AS  s    WITH (NOLOCK)ON    (r.ID_SACADO       =    s.ID_SACADO  AND S.ID_FUNDO = F.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML.dbo.TB_PORTE             AS  p    WITH (NOLOCK)ON    (p.ID_PORTE        =    s.ID_PORTE)
		LEFT JOIN		FIDC_CUSTODIA_HML.dbo.TB_CLASS_RISCO       AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO =    s.ID_CLASS_RISCO)
        INNER JOIN      FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTO    AS  tm   WITH (NOLOCK)ON    (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
		INNER JOIN      FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTACAO AS  tmm  WITH (NOLOCK)ON    (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
		WHERE m.DT    between @minDate and @maxDate
		AND   f.NU_CNPJ   =    @cnpjFundo
		AND   TMM.IC_BAIXAR_ATIVO = 1
		
		UNION ALL
		
		SELECT        DISTINCT
				'SACADO'										AS    TP_CLIENTE,
				CONVERT(VARCHAR(8), NULLIF(s.NU_CEP, ''))		COLLATE DATABASE_DEFAULT AS    CEP,
				CONVERT(VARCHAR(40), NULLIF(s.NM_CONG_ECON, ''))
																COLLATE DATABASE_DEFAULT AS    CONG_ECONOMICO,
				CONVERT(NUMERIC(19,4), ROUND(NULLIF(s.VL_FAT_ANUAL, 0.0),4))
																AS    VL_FAT_ANUAL,
				CONVERT(DATE, s.DT_INI_RELACIONAMENTO)			AS    DT_INI_RELAC,
				CONVERT(VARCHAR(2), NULLIF(s.DS_ESTADO,''))		COLLATE DATABASE_DEFAULT AS    CD_LOCALIZACAO,	-- ANEXO 07
				CONVERT(VARCHAR(2), NULL)						AS    CD_TP_CONTROLE,	-- ANEXO 10
				CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN '1' 
										 WHEN s.IC_TIPO_PESSOA = 1 THEN '2'
										 ELSE NULL
									END)						COLLATE DATABASE_DEFAULT AS    CD_TP_PESSOA,		-- ANEXO 11
				CONVERT(VARCHAR(2), cl.CD_CLASS_RISCO)			COLLATE DATABASE_DEFAULT AS    CD_RATING,		-- ANEXO 16
				CONVERT(VARCHAR(1), s.IC_AUTORIZACAO)			AS    CD_AUTORIZACAO,	-- ANEXO 20
				CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 1 THEN p.CD_SUB_PORTE ELSE NULL END)
																AS    CD_PORTE_PJ,		-- ANEXO 24
				CONVERT(VARCHAR(1), CASE WHEN s.IC_TIPO_PESSOA = 0 THEN p.CD_SUB_PORTE ELSE NULL END)
																AS    CD_PORTE_PF,		-- ANEXO 25
				CONVERT(VARCHAR(14), s.NU_CPF_CNPJ)				COLLATE DATABASE_DEFAULT AS    DOC_CLIENTE,
				CONVERT(VARCHAR(100), s.NM_SACADO)				COLLATE DATABASE_DEFAULT AS    NM_CLIENTE,
						CASE WHEN s.ID_TIPO_SOCIEDADE = 14 THEN 1 ELSE 0 END AS    IS_SFN
		FROM			FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO         AS  m    WITH (NOLOCK)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO             AS  f    WITH (NOLOCK)ON    (m.ID_FUNDO        =    f.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL         AS  r    WITH (NOLOCK)ON    (r.ID_RECEBIVEL    =    m.ID_RECEBIVEL)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_FUNDO_SACADO      AS  s    WITH (NOLOCK)ON    (r.ID_SACADO       =    s.ID_SACADO  AND S.ID_FUNDO = F.ID_FUNDO)
		INNER JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_PORTE             AS  p    WITH (NOLOCK)ON    (p.ID_PORTE        =    s.ID_PORTE)
		LEFT JOIN		FIDC_CUSTODIA_HML_2.dbo.TB_CLASS_RISCO       AS  cl   WITH (NOLOCK)ON    (cl.ID_CLASS_RISCO =    s.ID_CLASS_RISCO)
        INNER JOIN      FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTO    AS  tm   WITH (NOLOCK)ON    (tm.ID_TIPO_MOVIMENTO     =    m.ID_TIPO_MOVIMENTO)
		INNER JOIN      FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTACAO AS  tmm  WITH (NOLOCK)ON    (tmm.CD_TIPO_MOVIMENTACAO =    tm.CD_TIPO_MOVIMENTACAO)
		WHERE m.DT    between @minDate and @maxDate
		AND   f.NU_CNPJ   =    @cnpjFundo
		AND   TMM.IC_BAIXAR_ATIVO = 1
		
    
			SET @qtImpCli = @qtImpCli + @@ROWCOUNT
			SET @dtImpCli = GETDATE()

			IF (@debug = 1)
			BEGIN
				PRINT 'Total de clientes: ' + CONVERT(varchar, @qtImpCli)
			END
	END


------------------------------------INICIO:::::   SETANDO VALORES DE PERCENTUAL DE COOBRIGAÇÃO
			CREATE TABLE #PERCENTUAIS(PERC_COOBRIGACAO   NUMERIC(17,2),
			                          DS_SEU_NUMERO	     VARCHAR(25))


			IF @ID_FUNDO_CUSTODIA IS NOT NULL
			BEGIN
			   
			    INSERT #PERCENTUAIS
				SELECT ((SELECT COUNT(R2.IC_COOBRIGACAO) 
						 FROM FIDC_CUSTODIA_HML.DBO.TB_RECEBIVEL  AS R2 
						 WHERE R2.DS_NU_DOCUMENTO COLLATE DATABASE_DEFAULT = IOP.DS_NU_DOCUMENTO 
						 AND R2.IC_COOBRIGACAO = 1
						 AND R2.ID_FUNDO = @ID_FUNDO_CUSTODIA
						 GROUP BY IC_COOBRIGACAO)) / COUNT(NU_PARCELA) AS PERC_COOBRIGACAO , 
						 R.DS_SEU_NUMERO COLLATE DATABASE_DEFAULT
				FROM FIDC_CUSTODIA_HML.DBO.TB_RECEBIVEL   AS R    WITH (NOLOCK)
				INNER JOIN TB_3040_IMP_OPERACAO               AS IOP  WITH (NOLOCK) ON(R.DS_NU_DOCUMENTO COLLATE DATABASE_DEFAULT = IOP.DS_NU_DOCUMENTO)
				WHERE R.ID_FUNDO = @ID_FUNDO_CUSTODIA
				GROUP BY R.NU_PARCELA,
						 IC_COOBRIGACAO,
						 IOP.DS_NU_DOCUMENTO, 
						 R.DS_SEU_NUMERO
			END
			ELSE
			BEGIN

			    INSERT #PERCENTUAIS
				SELECT ((SELECT COUNT(R2.IC_COOBRIGACAO) 
						 FROM FIDC_CUSTODIA_HML_2.DBO.TB_RECEBIVEL  AS R2 
						 WHERE R2.DS_NU_DOCUMENTO COLLATE DATABASE_DEFAULT = IOP.DS_NU_DOCUMENTO 
						 AND R2.IC_COOBRIGACAO = 1
						 AND R2.ID_FUNDO = @ID_FUNDO_CUSTODIA_2
						 GROUP BY IC_COOBRIGACAO)) / COUNT(NU_PARCELA) AS PERC_COOBRIGACAO , 
						 R.DS_SEU_NUMERO COLLATE DATABASE_DEFAULT
				FROM FIDC_CUSTODIA_HML_2.DBO.TB_RECEBIVEL   AS R WITH (NOLOCK) 
				INNER JOIN TB_3040_IMP_OPERACAO                 AS IOP WITH (NOLOCK) ON(R.DS_NU_DOCUMENTO COLLATE DATABASE_DEFAULT = IOP.DS_NU_DOCUMENTO)
				WHERE R.ID_FUNDO = @ID_FUNDO_CUSTODIA_2
				GROUP BY R.NU_PARCELA,
						 IC_COOBRIGACAO,
						 IOP.DS_NU_DOCUMENTO, 
						 R.DS_SEU_NUMERO
			END

			WHILE EXISTS(SELECT TOP 1 * FROM #PERCENTUAIS)
			BEGIN
				DECLARE @SEUNUMERO VARCHAR(100),
				        @PERC INT

				SELECT TOP 1 @SEUNUMERO = DS_SEU_NUMERO,
					         @PERC = PERC_COOBRIGACAO
				FROM #PERCENTUAIS

				UPDATE TB_3040_IMP_OPERACAO	SET VL_PERC_COOBRIGACAO = @PERC
				WHERE CD_CONTRATO_CEDENTE = @SEUNUMERO

				DELETE FROM #PERCENTUAIS WHERE DS_SEU_NUMERO = @SEUNUMERO
				
			END
			
			DROP TABLE #PERCENTUAIS
------------------------------------FIM:::::   SETANDO VALORES DE PERCENTUAL DE COOBRIGAÇÃO


------------------------------------INICIO::::: VERIFICAR DATA E MES DA TB_3040_IMP_OPERACAO SEPARAR A ULTIMA MOVIMENTAÇÃO DE CADA RECEBIVEL
			CREATE TABLE #ULTIMA_MOVIMENTACAO_PADRONIZADO(ID_RECEBIVEL	     BIGINT,
			                                              ID_TIPO_MOVIMENTO	 INT,
														  IC_BAIXAR_ATIVO	 BIT,
														  IC_RECOMPRA	     BIT,
														  IC_AQUISICAO		 BIT)


			IF @ID_FUNDO_CUSTODIA IS NOT NULL
			BEGIN

			    INSERT #ULTIMA_MOVIMENTACAO_PADRONIZADO
				SELECT r.ID_RECEBIVEL
					  ,m.ID_TIPO_MOVIMENTO
					  ,mc.IC_BAIXAR_ATIVO
					  ,mc.IC_RECOMPRA
					  ,mc.IC_AQUISICAO
				FROM TB_3040_IMP_OPERACAO o
				INNER JOIN   FIDC_CUSTODIA_HML.dbo.TB_RECEBIVEL			 AS r   WITH (NOLOCK) ON  (r.ID_RECEBIVEL		= o.ID_RECEBIVEL)    
				INNER JOIN	(SELECT ID_RECEBIVEL, MAX(ID_MOVIMENTO) AS ID_MOVIMENTO FROM FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO mov GROUP BY ID_RECEBIVEL) AS mov ON mov.ID_RECEBIVEL = r.ID_RECEBIVEL		
				INNER JOIN   FIDC_CUSTODIA_HML.dbo.TB_MOVIMENTO 		 AS m   WITH (NOLOCK) ON  (m.ID_MOVIMENTO		= mov.ID_MOVIMENTO)    
				INNER JOIN   FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTO     AS tm  WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO = m.ID_TIPO_MOVIMENTO)
				INNER JOIN   FIDC_CUSTODIA_HML.dbo.TB_TIPO_MOVIMENTACAO  AS mc  WITH (NOLOCK) ON  (mc.CD_TIPO_MOVIMENTACAO = tm.CD_TIPO_MOVIMENTACAO)
				WHERE R.ID_FUNDO = @ID_FUNDO_CUSTODIA

			END
			ELSE
			BEGIN

				INSERT #ULTIMA_MOVIMENTACAO_PADRONIZADO
                SELECT r.ID_RECEBIVEL
					  ,m.ID_TIPO_MOVIMENTO
					  ,mc.IC_BAIXAR_ATIVO
					  ,mc.IC_RECOMPRA
					  ,mc.IC_AQUISICAO
				FROM TB_3040_IMP_OPERACAO o
				INNER JOIN   FIDC_CUSTODIA_HML_2.dbo.TB_RECEBIVEL			 AS r   WITH (NOLOCK) ON  (r.ID_RECEBIVEL		= o.ID_RECEBIVEL)    
				INNER JOIN	(SELECT ID_RECEBIVEL, MAX(ID_MOVIMENTO) AS ID_MOVIMENTO FROM FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO mov GROUP BY ID_RECEBIVEL) AS mov ON mov.ID_RECEBIVEL = r.ID_RECEBIVEL		
				INNER JOIN   FIDC_CUSTODIA_HML_2.dbo.TB_MOVIMENTO 		 AS m   WITH (NOLOCK) ON  (m.ID_MOVIMENTO		= mov.ID_MOVIMENTO)    
				INNER JOIN   FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTO     AS tm  WITH (NOLOCK) ON  (tm.ID_TIPO_MOVIMENTO = m.ID_TIPO_MOVIMENTO)
				INNER JOIN   FIDC_CUSTODIA_HML_2.dbo.TB_TIPO_MOVIMENTACAO  AS mc  WITH (NOLOCK) ON  (mc.CD_TIPO_MOVIMENTACAO = tm.CD_TIPO_MOVIMENTACAO)
				WHERE R.ID_FUNDO = @ID_FUNDO_CUSTODIA_2

			END

			--DEFINE ANEXO 08 PARA OPERAÇÕES PRROROGADAS OU RENEGOCIADAS
			--UPDATE #IMP_OPERACAO_PADRONIZADO SET
			UPDATE TB_3040_IMP_OPERACAO SET CD_CARAC_ESPEC = '1'
			WHERE ID_RECEBIVEL IN(SELECT ID_RECEBIVEL
								  FROM #ULTIMA_MOVIMENTACAO_PADRONIZADO 
								  WHERE IC_RECOMPRA = 1 AND IC_AQUISICAO = 1)

           DROP TABLE #ULTIMA_MOVIMENTACAO_PADRONIZADO
------------------------------------FIM:::::  VERIFICAR DATA E MES DA TB_3040_IMP_OPERACAO SEPARAR A ULTIMA MOVIMENTAÇÃO DE CADA RECEBIVEL

    INSERT INTO TB_3040_IMP_LOG VALUES (
        @idFundo,
        @qtImpOp, 
        CONVERT(VARCHAR, @dtImpOp - @inicio, 14),
        @qtImpCli, 
        CONVERT(VARCHAR, @dtImpCli - @dtImpOp, 14),
        null, 
        null,
        null, 
        null,
        CONVERT(VARCHAR, GETDATE() - @inicio, 14)
        )
    
    SET @cdError = 0;
    SET @dsError = 'Importação executada com sucesso'
    RETURN @cdError
END