/****** Object:  Table [dbo].[TB_3040_ARQUIVO_DP_TAXA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ARQUIVO_DP_TAXA](
	[ID_ARQUIVO_TAXA] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ARQUIVO] [int] NOT NULL,
	[CD_OPERACAO] [varchar](100) NOT NULL,
	[TP_ATIVO] [varchar](40) NOT NULL,
	[DS_CONTA_CETIP] [varchar](100) NOT NULL,
	[TP_MOVIMENTO] [varchar](40) NOT NULL,
	[TX_DESCONTO] [numeric](25, 10) NOT NULL,
	[TX_JUROS] [numeric](25, 10) NOT NULL,
 CONSTRAINT [PK__ARQUIVO_DP_TAXA] PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO_TAXA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_TAXA]  WITH CHECK ADD  CONSTRAINT [FK__ARQUIVO_DP_TAXA__ARQUIVO_DP] FOREIGN KEY([ID_ARQUIVO])
REFERENCES [dbo].[TB_3040_ARQUIVO_DP] ([ID_ARQUIVO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_TAXA] CHECK CONSTRAINT [FK__ARQUIVO_DP_TAXA__ARQUIVO_DP]