/****** Object:  Table [dbo].[TB_3040_DE_PARA_CLASS_RISCO_CLI]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_CLASS_RISCO_CLI](
	[ID_DE_PARA_CLASS_RISCO_CLI] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_16] [int] NOT NULL,
	[DS_CLASS_RISCO_CLI] [varchar](25) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_CLASS_RISCO_CLI] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_CLASS_RISCO_CLI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_CLASS_RISCO_CLI]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_CLASS_RISCO_CLI_ANEXO_16] FOREIGN KEY([ID_ANEXO_16])
REFERENCES [dbo].[TB_3040_ANEXO_16_CLASS_RISCO_CLI] ([ID_ANEXO_16])
ALTER TABLE [dbo].[TB_3040_DE_PARA_CLASS_RISCO_CLI] CHECK CONSTRAINT [FK__DE_PARA_CLASS_RISCO_CLI_ANEXO_16]