/****** Object:  Table [dbo].[TB_3040_ARQUIVO_DP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ARQUIVO_DP](
	[ID_ARQUIVO] [int] IDENTITY(1,1) NOT NULL,
	[ID_FUNDO] [int] NOT NULL,
	[DT_POSICAO] [date] NOT NULL,
	[TP_ARQUIVO] [varchar](10) NOT NULL,
	[NM_ARQUIVO] [varchar](255) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK__ARQUIVO_DP] PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP]  WITH CHECK ADD  CONSTRAINT [FK__ARQUIVO_DP__FUNDO] FOREIGN KEY([ID_FUNDO])
REFERENCES [dbo].[TB_3040_BAS_FUNDO] ([ID_FUNDO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP] CHECK CONSTRAINT [FK__ARQUIVO_DP__FUNDO]