/****** Object:  Table [dbo].[TB_3040_ARQUIVO_DP_OPERACAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ARQUIVO_DP_OPERACAO](
	[ID_ARQUIVO_OPERACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ARQUIVO] [int] NOT NULL,
	[CD_CONTRATO] [varchar](100) NOT NULL,
	[CD_SISTEMA_ORIGEM] [varchar](3) NOT NULL,
	[TP_ATIVO] [varchar](40) NOT NULL,
	[DS_CONTA_COSIF] [varchar](100) NOT NULL,
	[DT_AQUISICAO] [date] NOT NULL,
	[DT_VENCIMENTO] [date] NOT NULL,
	[DOC_ORIGINADOR] [varchar](14) NULL,
	[TX_OPERACAO] [numeric](25, 10) NOT NULL,
	[VL_CONTRATO] [numeric](19, 4) NOT NULL,
	[VL_NOMINAL] [numeric](19, 4) NOT NULL,
	[VL_PERC_INDEXADOR] [numeric](5, 2) NOT NULL,
	[VL_PDD] [numeric](19, 4) NOT NULL,
	[ID_OPERACAO] [bigint] NULL,
	[DOC_CLIENTE] [varchar](14) NOT NULL,
	[CD_NATUREZA] [varchar](2) NOT NULL,
	[CD_MODALIDADE] [varchar](4) NOT NULL,
	[CD_ORIGEM] [varchar](4) NOT NULL,
	[CD_INDEXADOR] [varchar](2) NOT NULL,
	[CD_VARIACAO_CAMBIAL] [varchar](3) NOT NULL,
	[CD_CARACTERISTICA] [varchar](2) NULL,
	[CD_CLASS_RISCO] [varchar](2) NOT NULL,
	[CD_VINCME] [varchar](1) NOT NULL,
	[CD_PRZ_PROVISIONAMENTO] [varchar](1) NOT NULL,
	[CD_DESEMPENHO] [varchar](2) NOT NULL,
 CONSTRAINT [PK__ARQUIVO_DP_OPERACAO] PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO_OPERACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_OPERACAO]  WITH CHECK ADD  CONSTRAINT [FK__ARQUIVO_DP_OPERACAO__ARQUIVO_DP] FOREIGN KEY([ID_ARQUIVO])
REFERENCES [dbo].[TB_3040_ARQUIVO_DP] ([ID_ARQUIVO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_OPERACAO] CHECK CONSTRAINT [FK__ARQUIVO_DP_OPERACAO__ARQUIVO_DP]