/****** Object:  Table [dbo].[TB_3040_XML_GAR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_XML_GAR](
	[ID_XML_GAR] [int] IDENTITY(1,1) NOT NULL,
	[DTREAV] [date] NULL,
	[IDENT] [varchar](14) NULL,
	[PERCGAR] [numeric](5, 0) NULL,
	[TP] [varchar](4) NULL,
	[VLRDATA] [numeric](19, 2) NULL,
	[VLRORIG] [numeric](19, 2) NULL,
	[ID_XML_OP] [int] NOT NULL,
 CONSTRAINT [PK__XML_GAR] PRIMARY KEY CLUSTERED 
(
	[ID_XML_GAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_XML_GAR]  WITH CHECK ADD  CONSTRAINT [FK__XML_GAR__XML_OP] FOREIGN KEY([ID_XML_OP])
REFERENCES [dbo].[TB_3040_XML_OP] ([ID_XML_OP])
ALTER TABLE [dbo].[TB_3040_XML_GAR] CHECK CONSTRAINT [FK__XML_GAR__XML_OP]