/****** Object:  Table [dbo].[TB_3040_DE_PARA_MODALIDADE_OPERACAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_MODALIDADE_OPERACAO](
	[ID_DE_PARA_MODALIDADE_OPERACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_03] [int] NOT NULL,
	[DS_MODALIDADE_OPERACAO] [varchar](200) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_MODALIDADE_OPERACAO] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_MODALIDADE_OPERACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_MODALIDADE_OPERACAO]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_MODALIDADE_OPERACAO_ANEXO_03] FOREIGN KEY([ID_ANEXO_03])
REFERENCES [dbo].[TB_3040_ANEXO_03_MODALIDADE_OPERACAO] ([ID_ANEXO_03])
ALTER TABLE [dbo].[TB_3040_DE_PARA_MODALIDADE_OPERACAO] CHECK CONSTRAINT [FK__DE_PARA_MODALIDADE_OPERACAO_ANEXO_03]