/****** Object:  Table [dbo].[TB_3040_DE_PARA_CARAC_ESPECIAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_CARAC_ESPECIAL](
	[ID_DE_PARA_CARAC_ESPECIAL] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_08] [int] NOT NULL,
	[DS_CARAC_ESPECIAL] [varchar](160) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_CARAC_ESPECIAL] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_CARAC_ESPECIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_CARAC_ESPECIAL]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_CARAC_ESPECIAL_ANEXO_08] FOREIGN KEY([ID_ANEXO_08])
REFERENCES [dbo].[TB_3040_ANEXO_08_CARAC_ESPECIAL] ([ID_ANEXO_08])
ALTER TABLE [dbo].[TB_3040_DE_PARA_CARAC_ESPECIAL] CHECK CONSTRAINT [FK__DE_PARA_CARAC_ESPECIAL_ANEXO_08]