/****** Object:  Table [dbo].[TB_3040_BAS_GARANTIA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_BAS_GARANTIA](
	[ID_GARANTIA] [bigint] IDENTITY(1,1) NOT NULL,
	[DT_REAVALIACAO] [date] NULL,
	[DS_GARANTIDOR] [varchar](14) NULL,
	[VL_PERC_GARANTIDO] [numeric](10, 7) NULL,
	[ID_ANEXO_12] [int] NOT NULL,
	[VL_ORIGINAL] [numeric](15, 4) NULL,
	[VL_REAVALIACAO] [numeric](15, 4) NULL,
	[ID_OPERACAO] [bigint] NULL,
	[ID_FUNDO] [int] NOT NULL,
	[DT_POSICAO] [date] NOT NULL,
	[CD_CONTRATO_CEDENTE] [varchar](100) NOT NULL,
	[CD_SISTEMA_ORIGEM] [varchar](10) NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__GARANTIA] PRIMARY KEY CLUSTERED 
(
	[ID_GARANTIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_BAS_GARANTIA]  WITH CHECK ADD  CONSTRAINT [PK__GARANTIA__FUNDO] FOREIGN KEY([ID_FUNDO])
REFERENCES [dbo].[TB_3040_BAS_FUNDO] ([ID_FUNDO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_BAS_GARANTIA] CHECK CONSTRAINT [PK__GARANTIA__FUNDO]