/****** Object:  Table [dbo].[TB_3040_BAS_FUNDO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_BAS_FUNDO](
	[ID_FUNDO] [int] IDENTITY(1,1) NOT NULL,
	[CD_CNPJ_FUNDO] [varchar](14) NOT NULL,
	[NM_FUNDO] [varchar](100) NOT NULL,
	[NM_CURTO] [varchar](15) NOT NULL,
	[NM_RESPONSAVEL] [varchar](100) NOT NULL,
	[EMAIL_RESPONSAVEL] [varchar](100) NOT NULL,
	[TEL_RESPONSAVEL] [varchar](15) NOT NULL,
	[DT_INICIO_VIGENCIA] [date] NOT NULL,
	[DT_FIM_VIGENCIA] [date] NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
	[TP_FUNDO] [varchar](max) NOT NULL,
	[CD_FUNDO] [varchar](20) NULL,
 CONSTRAINT [PK__FUNDO] PRIMARY KEY CLUSTERED 
(
	[ID_FUNDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_BAS_FUNDO] ADD  DEFAULT ('NORMAL') FOR [TP_FUNDO]