/****** Object:  Table [dbo].[TB_3040_DE_PARA_NATUREZA_OPERACAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_NATUREZA_OPERACAO](
	[ID_DE_PARA_NATUREZA_OPERACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_02] [int] NOT NULL,
	[DS_NATUREZA_OPERACAO] [varchar](200) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_NATUREZA_OPERACAO] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_NATUREZA_OPERACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_NATUREZA_OPERACAO]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_NATUREZA_OPERACAO_ANEXO_02] FOREIGN KEY([ID_ANEXO_02])
REFERENCES [dbo].[TB_3040_ANEXO_02_NATUREZA_OPERACAO] ([ID_ANEXO_02])
ALTER TABLE [dbo].[TB_3040_DE_PARA_NATUREZA_OPERACAO] CHECK CONSTRAINT [FK__DE_PARA_NATUREZA_OPERACAO_ANEXO_02]