/****** Object:  Table [dbo].[TB_3040_DP_PADRAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DP_PADRAO](
	[ID_DP_PADRAO] [int] IDENTITY(1,1) NOT NULL,
	[VL_PERC_INDEXADOR] [numeric](5, 2) NOT NULL,
	[VL_PERC_COOBRIGACAO] [numeric](5, 2) NOT NULL,
	[ID_FUNDO] [int] NOT NULL,
	[ID_ANEXO_02] [int] NOT NULL,
	[ID_ANEXO_03] [int] NOT NULL,
	[ID_ANEXO_04] [int] NOT NULL,
	[ID_ANEXO_05] [int] NOT NULL,
	[ID_ANEXO_06] [int] NOT NULL,
	[ID_ANEXO_07] [int] NOT NULL,
	[ID_ANEXO_08] [int] NULL,
	[ID_ANEXO_10] [int] NOT NULL,
	[ID_ANEXO_16] [int] NOT NULL,
	[ID_ANEXO_17] [int] NOT NULL,
	[ID_ANEXO_18] [int] NOT NULL,
	[ID_ANEXO_19] [int] NOT NULL,
	[ID_ANEXO_20] [int] NOT NULL,
	[ID_ANEXO_28] [int] NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DP_PADRAO] PRIMARY KEY CLUSTERED 
(
	[ID_DP_PADRAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_02] FOREIGN KEY([ID_ANEXO_02])
REFERENCES [dbo].[TB_3040_ANEXO_02_NATUREZA_OPERACAO] ([ID_ANEXO_02])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_02]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_03] FOREIGN KEY([ID_ANEXO_03])
REFERENCES [dbo].[TB_3040_ANEXO_03_MODALIDADE_OPERACAO] ([ID_ANEXO_03])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_03]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_04] FOREIGN KEY([ID_ANEXO_04])
REFERENCES [dbo].[TB_3040_ANEXO_04_ORIGEM_RECURSO] ([ID_ANEXO_04])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_04]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_05] FOREIGN KEY([ID_ANEXO_05])
REFERENCES [dbo].[TB_3040_ANEXO_05_TAXA_REF_INDEXADOR] ([ID_ANEXO_05])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_05]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_06] FOREIGN KEY([ID_ANEXO_06])
REFERENCES [dbo].[TB_3040_ANEXO_06_VAR_CAMBIAL] ([ID_ANEXO_06])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_06]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_07] FOREIGN KEY([ID_ANEXO_07])
REFERENCES [dbo].[TB_3040_ANEXO_07_LOCALIZACAO] ([ID_ANEXO_07])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_07]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_08] FOREIGN KEY([ID_ANEXO_08])
REFERENCES [dbo].[TB_3040_ANEXO_08_CARAC_ESPECIAL] ([ID_ANEXO_08])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_08]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_10] FOREIGN KEY([ID_ANEXO_10])
REFERENCES [dbo].[TB_3040_ANEXO_10_TP_CONTROLE] ([ID_ANEXO_10])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_10]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_16] FOREIGN KEY([ID_ANEXO_16])
REFERENCES [dbo].[TB_3040_ANEXO_16_CLASS_RISCO_CLI] ([ID_ANEXO_16])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_16]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_17] FOREIGN KEY([ID_ANEXO_17])
REFERENCES [dbo].[TB_3040_ANEXO_17_CLASS_RISCO_OPER] ([ID_ANEXO_17])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_17]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_18] FOREIGN KEY([ID_ANEXO_18])
REFERENCES [dbo].[TB_3040_ANEXO_18_VINC_ME] ([ID_ANEXO_18])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_18]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_19] FOREIGN KEY([ID_ANEXO_19])
REFERENCES [dbo].[TB_3040_ANEXO_19_PRAZO_PROV] ([ID_ANEXO_19])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_19]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_20] FOREIGN KEY([ID_ANEXO_20])
REFERENCES [dbo].[TB_3040_ANEXO_20_AUTORIZACAO] ([ID_ANEXO_20])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_20]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__ANEXO_28] FOREIGN KEY([ID_ANEXO_28])
REFERENCES [dbo].[TB_3040_ANEXO_28_DES_OPERACAO] ([ID_ANEXO_28])
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__ANEXO_28]
ALTER TABLE [dbo].[TB_3040_DP_PADRAO]  WITH CHECK ADD  CONSTRAINT [PK__DP_PADRAO__FUNDO] FOREIGN KEY([ID_FUNDO])
REFERENCES [dbo].[TB_3040_BAS_FUNDO] ([ID_FUNDO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_DP_PADRAO] CHECK CONSTRAINT [PK__DP_PADRAO__FUNDO]