/****** Object:  Table [dbo].[TB_3040_ANEXO_26_INFO_ADICIONAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ANEXO_26_INFO_ADICIONAL](
	[ID_ANEXO_26] [int] IDENTITY(1,1) NOT NULL,
	[CD_INFO_ADICIONAL] [varchar](2) NOT NULL,
	[CD_SUB_INFO_ADICIONAL] [varchar](2) NOT NULL,
	[DS_INFO_ADICIONAL] [varchar](150) NOT NULL,
	[DS_SUB_INFO_ADICIONAL] [varchar](200) NOT NULL,
	[IS_ATIVO] [bit] NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__ANEXO_26] PRIMARY KEY CLUSTERED 
(
	[ID_ANEXO_26] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]