/****** Object:  Table [dbo].[TB_3040_BAS_CLIENTE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_BAS_CLIENTE](
	[ID_CLIENTE] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_FUNDO] [int] NOT NULL,
	[TP_CLIENTE] [varchar](31) NOT NULL,
	[CEP] [varchar](8) NOT NULL,
	[CONG_ECONOMICO] [varchar](40) NULL,
	[VL_FAT_ANUAL] [numeric](19, 2) NULL,
	[DT_INI_RELAC] [date] NOT NULL,
	[ID_ANEXO_07] [int] NOT NULL,
	[ID_ANEXO_10] [int] NOT NULL,
	[ID_ANEXO_11] [int] NOT NULL,
	[ID_ANEXO_16] [int] NOT NULL,
	[ID_ANEXO_20] [int] NOT NULL,
	[ID_ANEXO_24] [int] NULL,
	[ID_ANEXO_25] [int] NULL,
	[DOC_CLIENTE] [varchar](14) NOT NULL,
	[NM_CLIENTE] [varchar](100) NOT NULL,
	[IS_SFN] [bit] NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
	[CD_SISTEMA_ORIGEM] [varchar](10) NULL,
	[CD_TP_PESSOA] [int] NULL,
 CONSTRAINT [PK__CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__TB_3040_BAS_CLIENTE__01] UNIQUE NONCLUSTERED 
(
	[ID_FUNDO] ASC,
	[TP_CLIENTE] ASC,
	[DOC_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX__TB_3040_BAS_CLIENTE_01] ON [dbo].[TB_3040_BAS_CLIENTE]
(
	[ID_FUNDO] ASC,
	[ID_CLIENTE] ASC
)
INCLUDE ( 	[DOC_CLIENTE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_07] FOREIGN KEY([ID_ANEXO_07])
REFERENCES [dbo].[TB_3040_ANEXO_07_LOCALIZACAO] ([ID_ANEXO_07])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_07]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_10] FOREIGN KEY([ID_ANEXO_10])
REFERENCES [dbo].[TB_3040_ANEXO_10_TP_CONTROLE] ([ID_ANEXO_10])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_10]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_11] FOREIGN KEY([ID_ANEXO_11])
REFERENCES [dbo].[TB_3040_ANEXO_11_TP_PESSOA] ([ID_ANEXO_11])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_11]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_16] FOREIGN KEY([ID_ANEXO_16])
REFERENCES [dbo].[TB_3040_ANEXO_16_CLASS_RISCO_CLI] ([ID_ANEXO_16])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_16]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_20] FOREIGN KEY([ID_ANEXO_20])
REFERENCES [dbo].[TB_3040_ANEXO_20_AUTORIZACAO] ([ID_ANEXO_20])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_20]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_24] FOREIGN KEY([ID_ANEXO_24])
REFERENCES [dbo].[TB_3040_ANEXO_24_PORTE_CLIENTE_PJ] ([ID_ANEXO_24])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_24]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__ANEXO_25] FOREIGN KEY([ID_ANEXO_25])
REFERENCES [dbo].[TB_3040_ANEXO_25_PORTE_CLIENTE_PF] ([ID_ANEXO_25])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__ANEXO_25]
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__CLIENTE__FUNDO] FOREIGN KEY([ID_FUNDO])
REFERENCES [dbo].[TB_3040_BAS_FUNDO] ([ID_FUNDO])
ALTER TABLE [dbo].[TB_3040_BAS_CLIENTE] CHECK CONSTRAINT [FK__CLIENTE__FUNDO]