/****** Object:  Table [dbo].[TB_3040_ATIVO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ATIVO](
	[ID_ATIVO] [int] IDENTITY(1,1) NOT NULL,
	[ID_FUNDO] [int] NOT NULL,
	[CD_ATIVO] [varchar](40) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__ATIVO_SAC] PRIMARY KEY CLUSTERED 
(
	[ID_ATIVO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_ATIVO]  WITH CHECK ADD  CONSTRAINT [FK__ATIVO_SAC__FUNDO] FOREIGN KEY([ID_FUNDO])
REFERENCES [dbo].[TB_3040_BAS_FUNDO] ([ID_FUNDO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_ATIVO] CHECK CONSTRAINT [FK__ATIVO_SAC__FUNDO]