/****** Object:  Table [dbo].[TB_3040_BAS_INFORMACAO_ADICIONAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_BAS_INFORMACAO_ADICIONAL](
	[ID_INF_ADD] [bigint] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](40) NULL,
	[IDENTIFICACAO] [varchar](14) NULL,
	[PERCENTUAL] [numeric](10, 7) NULL,
	[QUANTIDADE] [bigint] NULL,
	[ID_ANEXO_26] [int] NOT NULL,
	[VALOR] [numeric](15, 4) NULL,
	[ID_OPERACAO] [bigint] NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__INFORMACAO_ADICIONAL] PRIMARY KEY CLUSTERED 
(
	[ID_INF_ADD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_BAS_INFORMACAO_ADICIONAL]  WITH CHECK ADD  CONSTRAINT [PK__INF_ADICIONAL__ANEXO_26] FOREIGN KEY([ID_ANEXO_26])
REFERENCES [dbo].[TB_3040_ANEXO_26_INFO_ADICIONAL] ([ID_ANEXO_26])
ALTER TABLE [dbo].[TB_3040_BAS_INFORMACAO_ADICIONAL] CHECK CONSTRAINT [PK__INF_ADICIONAL__ANEXO_26]
ALTER TABLE [dbo].[TB_3040_BAS_INFORMACAO_ADICIONAL]  WITH CHECK ADD  CONSTRAINT [PK__INF_ADICIONAL__OPERACAO] FOREIGN KEY([ID_OPERACAO])
REFERENCES [dbo].[TB_3040_BAS_OPERACAO] ([ID_OPERACAO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_BAS_INFORMACAO_ADICIONAL] CHECK CONSTRAINT [PK__INF_ADICIONAL__OPERACAO]