/****** Object:  Table [dbo].[TB_3040_DE_PARA_TAXA_REF_INDEXADOR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_TAXA_REF_INDEXADOR](
	[ID_DE_PARA_TAXA_REF_INDEXADOR] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_05] [int] NOT NULL,
	[DS_TAXA_REF_INDEXADOR] [varchar](15) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_TAXA_REF_INDEXADOR] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_TAXA_REF_INDEXADOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_TAXA_REF_INDEXADOR]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_TAXA_REF_INDEXADOR_ANEXO_05] FOREIGN KEY([ID_ANEXO_05])
REFERENCES [dbo].[TB_3040_ANEXO_05_TAXA_REF_INDEXADOR] ([ID_ANEXO_05])
ALTER TABLE [dbo].[TB_3040_DE_PARA_TAXA_REF_INDEXADOR] CHECK CONSTRAINT [FK__DE_PARA_TAXA_REF_INDEXADOR_ANEXO_05]