/****** Object:  Table [dbo].[TB_3040_BAS_OPERACAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_BAS_OPERACAO](
	[ID_OPERACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_FUNDO] [int] NOT NULL,
	[DT_POSICAO] [date] NOT NULL,
	[CD_CONTRATO_CEDENTE] [varchar](100) NOT NULL,
	[CD_CONTRATO_SACADO] [varchar](100) NOT NULL,
	[CD_LASTRO] [varchar](100) NULL,
	[DOC_ORIGINADOR] [varchar](14) NULL,
	[ID_SISTEMA_ORIGEM] [varchar](100) NOT NULL,
	[CD_SISTEMA_ORIGEM] [varchar](10) NOT NULL,
	[TP_ATIVO] [varchar](40) NOT NULL,
	[DS_CONTA_COSIF] [varchar](100) NOT NULL,
	[FL_COOBRIGACAO] [bit] NOT NULL,
	[DT_AQUISICAO] [date] NOT NULL,
	[DT_VENCIMENTO] [date] NULL,
	[TX_OPERACAO] [numeric](25, 10) NOT NULL,
	[VL_AQUISICAO] [numeric](19, 4) NULL,
	[VL_NOMINAL] [numeric](19, 4) NULL,
	[VL_PERC_COOBRIGACAO] [numeric](10, 7) NULL,
	[VL_PERC_SUBORDINACAO] [numeric](10, 7) NULL,
	[VL_PDD] [numeric](19, 4) NOT NULL,
	[VL_PERC_INDEXADOR] [numeric](5, 2) NOT NULL,
	[ID_CEDENTE] [bigint] NOT NULL,
	[ID_SACADO] [bigint] NOT NULL,
	[ID_ANEXO_02] [int] NOT NULL,
	[ID_ANEXO_03] [int] NOT NULL,
	[ID_ANEXO_04] [int] NOT NULL,
	[ID_ANEXO_05] [int] NOT NULL,
	[ID_ANEXO_06] [int] NOT NULL,
	[ID_ANEXO_08] [int] NULL,
	[ID_ANEXO_17] [int] NOT NULL,
	[ID_ANEXO_18] [int] NOT NULL,
	[ID_ANEXO_19] [int] NOT NULL,
	[ID_ANEXO_28] [int] NULL,
	[FL_SUBSTITUIDO_FLUXO] [bit] NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
	[DS_NU_DOCUMENTO] [varchar](100) NULL,
	[CD_RATING] [varchar](255) NULL,
	[NUM_CONTRATO_C3] [varchar](21) NULL,
	[IC_BAIXAR_ATIVO] [bit] NOT NULL,
	[IC_RECOMPRA] [bit] NOT NULL,
	[VL_MOVIMENTACAO] [numeric](17, 2) NULL,
	[DT_MOVIMENTO] [smalldatetime] NULL,
	[NM_TIPO_MOVIMENTO] [varchar](100) NULL,
 CONSTRAINT [PK__OPERACAO] PRIMARY KEY CLUSTERED 
(
	[ID_OPERACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX__TB_3040_BAS_OPERACAO_01] ON [dbo].[TB_3040_BAS_OPERACAO]
(
	[ID_FUNDO] ASC,
	[DT_POSICAO] ASC,
	[FL_SUBSTITUIDO_FLUXO] ASC,
	[FL_COOBRIGACAO] ASC
)
INCLUDE ( 	[ID_OPERACAO],
	[CD_CONTRATO_CEDENTE],
	[CD_CONTRATO_SACADO],
	[CD_LASTRO],
	[DOC_ORIGINADOR],
	[ID_SISTEMA_ORIGEM],
	[CD_SISTEMA_ORIGEM],
	[TP_ATIVO],
	[DS_CONTA_COSIF],
	[DT_AQUISICAO],
	[DT_VENCIMENTO],
	[TX_OPERACAO],
	[VL_AQUISICAO],
	[VL_NOMINAL],
	[VL_PERC_COOBRIGACAO],
	[VL_PERC_SUBORDINACAO],
	[VL_PDD],
	[VL_PERC_INDEXADOR],
	[ID_CEDENTE],
	[ID_SACADO],
	[ID_ANEXO_02],
	[ID_ANEXO_03],
	[ID_ANEXO_04],
	[ID_ANEXO_05],
	[ID_ANEXO_06],
	[ID_ANEXO_08],
	[ID_ANEXO_17],
	[ID_ANEXO_18],
	[ID_ANEXO_19],
	[ID_ANEXO_28]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TB_3040_BAS_OPERACAO_2] ON [dbo].[TB_3040_BAS_OPERACAO]
(
	[ID_FUNDO] ASC,
	[CD_SISTEMA_ORIGEM] ASC
)
INCLUDE ( 	[ID_OPERACAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TB_3040_BAS_OPERACAO_3] ON [dbo].[TB_3040_BAS_OPERACAO]
(
	[ID_FUNDO] ASC,
	[FL_SUBSTITUIDO_FLUXO] ASC
)
INCLUDE ( 	[ID_OPERACAO],
	[DT_POSICAO],
	[CD_CONTRATO_CEDENTE],
	[CD_CONTRATO_SACADO],
	[CD_SISTEMA_ORIGEM],
	[TP_ATIVO],
	[VL_AQUISICAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] ADD  DEFAULT ((0)) FOR [IC_BAIXAR_ATIVO]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] ADD  DEFAULT ((0)) FOR [IC_RECOMPRA]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_02] FOREIGN KEY([ID_ANEXO_02])
REFERENCES [dbo].[TB_3040_ANEXO_02_NATUREZA_OPERACAO] ([ID_ANEXO_02])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_02]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_03] FOREIGN KEY([ID_ANEXO_03])
REFERENCES [dbo].[TB_3040_ANEXO_03_MODALIDADE_OPERACAO] ([ID_ANEXO_03])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_03]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_04] FOREIGN KEY([ID_ANEXO_04])
REFERENCES [dbo].[TB_3040_ANEXO_04_ORIGEM_RECURSO] ([ID_ANEXO_04])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_04]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_05] FOREIGN KEY([ID_ANEXO_05])
REFERENCES [dbo].[TB_3040_ANEXO_05_TAXA_REF_INDEXADOR] ([ID_ANEXO_05])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_05]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_06] FOREIGN KEY([ID_ANEXO_06])
REFERENCES [dbo].[TB_3040_ANEXO_06_VAR_CAMBIAL] ([ID_ANEXO_06])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_06]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_08] FOREIGN KEY([ID_ANEXO_08])
REFERENCES [dbo].[TB_3040_ANEXO_08_CARAC_ESPECIAL] ([ID_ANEXO_08])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_08]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_17] FOREIGN KEY([ID_ANEXO_17])
REFERENCES [dbo].[TB_3040_ANEXO_17_CLASS_RISCO_OPER] ([ID_ANEXO_17])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_17]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_18] FOREIGN KEY([ID_ANEXO_18])
REFERENCES [dbo].[TB_3040_ANEXO_18_VINC_ME] ([ID_ANEXO_18])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_18]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_19] FOREIGN KEY([ID_ANEXO_19])
REFERENCES [dbo].[TB_3040_ANEXO_19_PRAZO_PROV] ([ID_ANEXO_19])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_19]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__ANEXO_28] FOREIGN KEY([ID_ANEXO_28])
REFERENCES [dbo].[TB_3040_ANEXO_28_DES_OPERACAO] ([ID_ANEXO_28])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__ANEXO_28]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__CEDENTE] FOREIGN KEY([ID_CEDENTE])
REFERENCES [dbo].[TB_3040_BAS_CLIENTE] ([ID_CLIENTE])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__CEDENTE]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__FUNDO] FOREIGN KEY([ID_FUNDO])
REFERENCES [dbo].[TB_3040_BAS_FUNDO] ([ID_FUNDO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__FUNDO]
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO]  WITH CHECK ADD  CONSTRAINT [PK__OPERACAO__SACADO] FOREIGN KEY([ID_SACADO])
REFERENCES [dbo].[TB_3040_BAS_CLIENTE] ([ID_CLIENTE])
ALTER TABLE [dbo].[TB_3040_BAS_OPERACAO] CHECK CONSTRAINT [PK__OPERACAO__SACADO]