/****** Object:  Table [dbo].[TB_3040_DE_PARA_VINC_ME]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_VINC_ME](
	[ID_DE_PARA_VINC_ME] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_18] [int] NOT NULL,
	[DS_VINC_ME] [varchar](25) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_VINC_ME] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_VINC_ME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_VINC_ME]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_VINC_ME_ANEXO_18] FOREIGN KEY([ID_ANEXO_18])
REFERENCES [dbo].[TB_3040_ANEXO_18_VINC_ME] ([ID_ANEXO_18])
ALTER TABLE [dbo].[TB_3040_DE_PARA_VINC_ME] CHECK CONSTRAINT [FK__DE_PARA_VINC_ME_ANEXO_18]