/****** Object:  Table [dbo].[TB_3040_ARQUIVO_DP_GARANTIA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ARQUIVO_DP_GARANTIA](
	[ID_ARQUIVO_GARANTIA] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ARQUIVO] [int] NOT NULL,
	[CD_LASTRO] [varchar](100) NOT NULL,
	[DS_CONTA_CETIP] [varchar](100) NOT NULL,
	[DOC_EMISSOR] [varchar](14) NOT NULL,
	[TP_ATIVO] [varchar](40) NOT NULL,
	[DS_DESCRICAO] [varchar](100) NOT NULL,
	[DS_SUB_DESCRICAO] [varchar](100) NOT NULL,
	[DOC_GARANTIDOR] [varchar](14) NULL,
	[VL_PERC_GARANTIDO] [numeric](10, 7) NULL,
	[VL_ORIGINAL] [numeric](15, 4) NULL,
	[VL_REAVALIACAO] [numeric](15, 4) NULL,
	[DT_REAVALIACAO] [date] NULL,
 CONSTRAINT [PK__ARQUIVO_DP_GARANTIA] PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO_GARANTIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_GARANTIA]  WITH CHECK ADD  CONSTRAINT [FK__ARQUIVO_DP_GARANTIA__ARQUIVO_DP] FOREIGN KEY([ID_ARQUIVO])
REFERENCES [dbo].[TB_3040_ARQUIVO_DP] ([ID_ARQUIVO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_GARANTIA] CHECK CONSTRAINT [FK__ARQUIVO_DP_GARANTIA__ARQUIVO_DP]