/****** Object:  Table [dbo].[TB_3040_ANEXO_03_MODALIDADE_OPERACAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ANEXO_03_MODALIDADE_OPERACAO](
	[ID_ANEXO_03] [int] IDENTITY(1,1) NOT NULL,
	[CD_MODALIDADE] [varchar](2) NOT NULL,
	[CD_SUB_MODALIDADE] [varchar](2) NOT NULL,
	[DS_MODALIDADE] [varchar](50) NOT NULL,
	[DS_SUB_MODALIDADE] [varchar](200) NOT NULL,
	[IS_ATIVO] [bit] NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__ANEXO_03] PRIMARY KEY CLUSTERED 
(
	[ID_ANEXO_03] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]