/****** Object:  Table [dbo].[TB_3040_DE_PARA_INFO_ADICIONAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_DE_PARA_INFO_ADICIONAL](
	[ID_DE_PARA_INFO_ADICIONAL] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ANEXO_26] [int] NOT NULL,
	[DS_INFO_ADICIONAL] [varchar](150) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__DE_PARA_INFO_ADICIONAL] PRIMARY KEY CLUSTERED 
(
	[ID_DE_PARA_INFO_ADICIONAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_DE_PARA_INFO_ADICIONAL]  WITH CHECK ADD  CONSTRAINT [FK__DE_PARA_INFO_ADICIONAL_ANEXO_26] FOREIGN KEY([ID_ANEXO_26])
REFERENCES [dbo].[TB_3040_ANEXO_26_INFO_ADICIONAL] ([ID_ANEXO_26])
ALTER TABLE [dbo].[TB_3040_DE_PARA_INFO_ADICIONAL] CHECK CONSTRAINT [FK__DE_PARA_INFO_ADICIONAL_ANEXO_26]