/****** Object:  Table [dbo].[TB_3040_XML]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_XML](
	[ID_XML] [int] IDENTITY(1,1) NOT NULL,
	[CNPJ] [varchar](14) NOT NULL,
	[DTBASE] [date] NOT NULL,
	[EMAILRESP] [varchar](100) NULL,
	[NOMERESP] [varchar](100) NULL,
	[PARTE] [int] NULL,
	[REMESSA] [int] NULL,
	[TELRESP] [varchar](50) NULL,
	[TOTALCLI] [int] NULL,
	[TPARQ] [varchar](1) NULL,
	[DOC3040] [xml] NULL,
 CONSTRAINT [PK__XML] PRIMARY KEY CLUSTERED 
(
	[ID_XML] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]