/****** Object:  Table [dbo].[TB_3040_ARQUIVO_DP_CLIENTE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_ARQUIVO_DP_CLIENTE](
	[ID_ARQUIVO_CLIENTE] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_ARQUIVO] [int] NOT NULL,
	[ID_CLIENTE] [bigint] NOT NULL,
	[DOC_CLIENTE] [varchar](14) NOT NULL,
	[NM_CLIENTE] [varchar](100) NOT NULL,
	[CEP] [varchar](8) NOT NULL,
	[CONG_ECONOMICO] [varchar](40) NULL,
	[VL_FAT_ANUAL] [numeric](19, 2) NULL,
	[DT_INI_RELAC] [date] NOT NULL,
	[CD_LOCALIZACAO] [varchar](5) NOT NULL,
	[CD_TP_CONTROLE] [varchar](2) NOT NULL,
	[CD_TP_PESSOA] [varchar](1) NOT NULL,
	[CD_CLASS_RISCO] [varchar](2) NOT NULL,
	[CD_AUTORIZACAO] [varchar](1) NOT NULL,
	[CD_PORTE_PJ] [varchar](1) NULL,
	[CD_PORTE_PF] [varchar](1) NULL,
	[IS_SFN] [bit] NOT NULL,
 CONSTRAINT [PK__ARQUIVO_DP_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK__ARQUIVO_DP_CLIENTE__ARQUIVO_DP] FOREIGN KEY([ID_ARQUIVO])
REFERENCES [dbo].[TB_3040_ARQUIVO_DP] ([ID_ARQUIVO])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_3040_ARQUIVO_DP_CLIENTE] CHECK CONSTRAINT [FK__ARQUIVO_DP_CLIENTE__ARQUIVO_DP]