/****** Object:  Table [dbo].[TB_3040_XML_INF]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_3040_XML_INF](
	[ID_XML_INF] [int] IDENTITY(1,1) NOT NULL,
	[CD] [varchar](40) NULL,
	[IDENT] [varchar](14) NULL,
	[PERC] [numeric](5, 2) NULL,
	[QTD] [int] NULL,
	[TP] [varchar](4) NULL,
	[VALOR] [numeric](19, 2) NULL,
	[ID_XML_OP] [int] NOT NULL,
 CONSTRAINT [PK__XML_INF] PRIMARY KEY CLUSTERED 
(
	[ID_XML_INF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_XML_INF_1] ON [dbo].[TB_3040_XML_INF]
(
	[ID_XML_OP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[TB_3040_XML_INF]  WITH CHECK ADD  CONSTRAINT [FK__XML_IINF__XML_OP] FOREIGN KEY([ID_XML_OP])
REFERENCES [dbo].[TB_3040_XML_OP] ([ID_XML_OP])
ALTER TABLE [dbo].[TB_3040_XML_INF] CHECK CONSTRAINT [FK__XML_IINF__XML_OP]