/****** Object:  Table [dbo].[TB_BATCH_STATUS_DETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_BATCH_STATUS_DETAIL](
	[ID_BATCH_STATUS_DETAIL] [bigint] IDENTITY(1,1) NOT NULL,
	[NM_ATRIBUTO] [varchar](50) NOT NULL,
	[VALOR] [varchar](255) NULL,
	[ID_BATCH_STATUS] [bigint] NULL,
 CONSTRAINT [PK__BATCH_STATUS_DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID_BATCH_STATUS_DETAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_BATCH_STATUS_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK__BATCH_STATUS_DETAIL__BATCH_STATUS] FOREIGN KEY([ID_BATCH_STATUS])
REFERENCES [dbo].[TB_BATCH_STATUS] ([ID_BATCH_STATUS])
ON DELETE CASCADE
ALTER TABLE [dbo].[TB_BATCH_STATUS_DETAIL] CHECK CONSTRAINT [FK__BATCH_STATUS_DETAIL__BATCH_STATUS]