/****** Object:  Table [dbo].[TB_FERIADO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_FERIADO](
	[ID_FERIADO] [int] IDENTITY(1,1) NOT NULL,
	[DT_FERIADO] [date] NOT NULL,
	[NM_FERIADO] [varchar](30) NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](100) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[ID_LOCALIDADE] [int] NOT NULL,
 CONSTRAINT [PK__FERIADO] PRIMARY KEY CLUSTERED 
(
	[ID_FERIADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC__TB_FERIADO] UNIQUE NONCLUSTERED 
(
	[DT_FERIADO] ASC,
	[ID_LOCALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_FERIADO]  WITH CHECK ADD  CONSTRAINT [FK__TB_FERIADO_LOCALIDADE] FOREIGN KEY([ID_LOCALIDADE])
REFERENCES [dbo].[TB_LOCALIDADE] ([ID_LOCALIDADE])
ALTER TABLE [dbo].[TB_FERIADO] CHECK CONSTRAINT [FK__TB_FERIADO_LOCALIDADE]