/****** Object:  Table [dbo].[TB_LOG_AUTENTICACAO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_LOG_AUTENTICACAO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SISTEMA] [varchar](50) NOT NULL,
	[USUARIO] [varchar](50) NOT NULL,
	[ULTIMO_LOGIN] [datetime2](7) NOT NULL,
	[NM_LOG] [varchar](100) NOT NULL,
 CONSTRAINT [PK__LOG_AUTENTICACAO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]