/****** Object:  Table [dbo].[TB_PARAMETRO_AUD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_PARAMETRO_AUD](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[REV] [int] NOT NULL,
	[ID_PARAMETRO] [int] NULL,
	[NM_PARAMETRO] [varchar](50) NULL,
	[parametro_MOD] [bit] NULL,
	[nome_MOD] [bit] NULL,
	[VALOR] [varchar](150) NULL,
	[valor_MOD] [bit] NULL,
	[CREATED_BY] [varchar](100) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[LAST_MODIFIED_BY] [varchar](100) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[REVTYPE] [tinyint] NULL,
 CONSTRAINT [PK__PARAMETRO_AUD] PRIMARY KEY CLUSTERED 
(
	[id] ASC,
	[REV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_PARAMETRO_AUD]  WITH CHECK ADD  CONSTRAINT [FK__PARAMETRO_AUD_REVINFO] FOREIGN KEY([REV])
REFERENCES [dbo].[REVINFO] ([REV])
ALTER TABLE [dbo].[TB_PARAMETRO_AUD] CHECK CONSTRAINT [FK__PARAMETRO_AUD_REVINFO]